import { useEffect, useState } from 'react'
import { apiGet, apiPatch } from '../../../lib/api'

export default function FreeDemoManager(){
  const[rows,setRows]=useState<any[]>([]),[message,setMessage]=useState('')
  const load=async()=>{const j:any=await apiGet('/me/free-demos');if(j?.ok)setRows(j.data||[]);else setMessage(j?.error||'No tienes acceso a este módulo.')}
  useEffect(()=>{void load()},[])
  const update=(id:string,key:string,value:any)=>setRows(r=>r.map(x=>x.id===id?{...x,[key]:value}:x))
  const save=async(row:any)=>{setMessage('');const j:any=await apiPatch('/me/free-demos/'+encodeURIComponent(row.id),{slug:row.slug,name:row.name,bio:row.bio,whatsapp:row.whatsapp,phone:row.phone,email:row.email,address:row.address,is_published:!!row.is_published});if(j?.ok){setMessage('Demo actualizada.');await load()}else setMessage(j?.error||'No se pudo guardar.')}
  const web=(import.meta.env.VITE_WEB_URL||'https://intaprd.com').replace(/\/$/,'')
  return <main className="min-h-screen bg-[#f7f9fc] p-5 text-slate-950"><section className="mx-auto max-w-5xl"><header className="mb-6"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-700">KAWVO LINK</p><h1 className="mt-2 text-3xl font-black">Mis perfiles Demo Free</h1><p className="mt-2 text-sm text-slate-600">Grupo especial de demostraciones administrado por intapcard@gmail.com. Los perfiles reclamados salen automáticamente de este listado.</p></header>{message&&<div className="mb-4 rounded-2xl bg-cyan-50 p-4 text-sm font-bold text-cyan-800">{message}</div>}<div className="space-y-4">{rows.map(r=><article key={r.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><strong>{r.name||r.slug}</strong><p className="text-xs text-slate-500">{r.rubric} · {r.status} {r.public_code?'· '+r.public_code:''}</p></div><a href={web+'/'+r.slug} target="_blank" rel="noreferrer" className="rounded-xl border px-3 py-2 text-sm font-bold">Ver perfil</a></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="rounded-xl border p-3" value={r.name||''} onChange={e=>update(r.id,'name',e.target.value)} placeholder="Nombre"/><input className="rounded-xl border p-3" value={r.slug||''} onChange={e=>update(r.id,'slug',e.target.value)} placeholder="slug"/><input className="rounded-xl border p-3" value={r.whatsapp||''} onChange={e=>update(r.id,'whatsapp',e.target.value)} placeholder="WhatsApp"/><input className="rounded-xl border p-3" value={r.email||''} onChange={e=>update(r.id,'email',e.target.value)} placeholder="Correo de contacto"/><input className="rounded-xl border p-3 md:col-span-2" value={r.address||''} onChange={e=>update(r.id,'address',e.target.value)} placeholder="Ubicación"/><textarea className="rounded-xl border p-3 md:col-span-2" value={r.bio||''} onChange={e=>update(r.id,'bio',e.target.value)} rows={3}/></div><div className="mt-4 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={!!r.is_published} onChange={e=>update(r.id,'is_published',e.target.checked)}/>Publicado</label><button onClick={()=>save(r)} className="rounded-xl bg-slate-950 px-4 py-3 font-black text-white">Guardar</button></div></article>)}{rows.length===0&&<div className="rounded-3xl bg-white p-8 text-center text-slate-500">No hay perfiles Demo Free pendientes de reclamo.</div>}</div></section></main>
}
