import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { apiPost } from '../../../lib/api'

export default function FreeTeamRoleLogin(){
  const { slug='' }=useParams();const navigate=useNavigate();const [password,setPassword]=useState('');const [nextPassword,setNextPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [mustChange,setMustChange]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{setPassword('');setMustChange(false);setError('')},[slug])
  const login=async()=>{if(busy||!password)return;setBusy(true);setError('');const json:any=await apiPost('/public/team/member-access/login',{slug,password}).catch(()=>({ok:false}));setBusy(false);if(!json?.ok){setError(json?.error||'No pudimos iniciar sesión.');return}if(json.data?.must_change_password){setMustChange(true);return}navigate('/admin/free/team',{replace:true})}
  const change=async()=>{if(busy)return;if(nextPassword.length<8){setError('La nueva contraseña debe tener al menos 8 caracteres.');return}if(nextPassword!==confirmPassword){setError('Las contraseñas no coinciden.');return}setBusy(true);setError('');const json:any=await apiPost('/me/team/access/change-password',{password:nextPassword}).catch(()=>({ok:false}));setBusy(false);if(!json?.ok){setError(json?.error||'No pudimos cambiar la contraseña.');return}navigate('/admin/free/team',{replace:true})}
  return <main className="min-h-screen bg-[#f7f9fc] px-5 py-8 font-['Inter'] text-slate-950"><section className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-[430px] flex-col justify-center"><div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_18px_55px_rgba(15,23,42,0.08)]"><p className="text-[11px] font-black uppercase tracking-[0.2em] text-cyan-700">KAWVO LINK · TEAM</p>{!mustChange?<><h1 className="mt-2 text-2xl font-black">Acceso administrativo</h1><p className="mt-2 text-sm leading-6 text-slate-500">Este acceso está disponible únicamente para Editor o Subadministrador autorizado.</p><label className="mt-5 block text-xs font-black text-slate-600">Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void login()}} autoComplete="current-password" className="mt-1 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm"/></label>{error&&<p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">{error}</p>}<button type="button" onClick={()=>void login()} disabled={busy||!password} className="mt-5 w-full rounded-2xl bg-slate-950 px-4 py-4 text-sm font-black text-white disabled:opacity-40">{busy?'Accediendo…':'Iniciar sesión'}</button></>:<><h1 className="mt-2 text-2xl font-black">Crea tu contraseña</h1><p className="mt-2 text-sm leading-6 text-slate-500">Por seguridad, reemplaza la contraseña temporal antes de entrar al panel.</p><label className="mt-5 block text-xs font-black text-slate-600">Nueva contraseña<input type="password" value={nextPassword} onChange={e=>setNextPassword(e.target.value)} autoComplete="new-password" className="mt-1 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm"/></label><label className="mt-3 block text-xs font-black text-slate-600">Confirmar contraseña<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password" className="mt-1 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3.5 text-sm"/></label>{error&&<p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">{error}</p>}<button type="button" onClick={()=>void change()} disabled={busy||!nextPassword||!confirmPassword} className="mt-5 w-full rounded-2xl bg-slate-950 px-4 py-4 text-sm font-black text-white disabled:opacity-40">{busy?'Guardando…':'Guardar contraseña y continuar'}</button></>}</div></section></main>
}