import { FaEdit, FaMapMarkerAlt, FaPlus, FaUniversity } from 'react-icons/fa'
import type { FreeProfileAppearanceColors } from '../free-profile/IntapLinkGratis.types'

export type TrialBank={id:string;bank_name:string;account_number:string;account_type:'savings'|'checking';currency:'DOP'|'USD';holder_name:string;display_mode:'masked'|'visible'}
export const TRIAL_PALETTES:Array<{id:string;name:string;colors:FreeProfileAppearanceColors}>=[
{id:'kawvo',name:'Kawvo',colors:{primary:'#071F5F',secondary:'#0B61C9',accent:'#10B981',button:'#0B61C9',background:'#F8FAFC',surface:'#FFFFFF',text:'#0F172A',heroGradient:'#071F5F'}},
{id:'oceano',name:'Océano',colors:{primary:'#0C4A6E',secondary:'#0284C7',accent:'#0891B2',button:'#0284C7',background:'#F0F9FF',surface:'#FFFFFF',text:'#0F172A',heroGradient:'#0C4A6E'}},
{id:'esmeralda',name:'Esmeralda',colors:{primary:'#064E3B',secondary:'#047857',accent:'#10B981',button:'#047857',background:'#F0FDF4',surface:'#FFFFFF',text:'#0F172A',heroGradient:'#064E3B'}},
{id:'violeta',name:'Violeta',colors:{primary:'#4C1D95',secondary:'#7C3AED',accent:'#A855F7',button:'#7C3AED',background:'#FAF5FF',surface:'#FFFFFF',text:'#111827',heroGradient:'#4C1D95'}},
{id:'coral',name:'Coral',colors:{primary:'#9F1239',secondary:'#E11D48',accent:'#FB7185',button:'#E11D48',background:'#FFF1F2',surface:'#FFFFFF',text:'#111827',heroGradient:'#9F1239'}},
{id:'grafito',name:'Grafito',colors:{primary:'#111827',secondary:'#374151',accent:'#64748B',button:'#374151',background:'#F8FAFC',surface:'#FFFFFF',text:'#111827',heroGradient:'#111827'}},
{id:'arena',name:'Arena',colors:{primary:'#5C4033',secondary:'#8B6F47',accent:'#B08968',button:'#8B6F47',background:'#FFFBEB',surface:'#FFFFFF',text:'#292524',heroGradient:'#5C4033'}}]

export function TrialLocationPanel({query,setQuery,preview,setPreview,onConfirm}:{query:string;setQuery:(v:string)=>void;preview:string;setPreview:(v:string)=>void;onConfirm:()=>void}){
 const embed=preview?'https://www.google.com/maps?q='+encodeURIComponent(preview)+'&output=embed':''
 function current(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{setQuery('Ubicación actual');setPreview(p.coords.latitude.toFixed(6)+','+p.coords.longitude.toFixed(6))},()=>undefined,{enableHighAccuracy:true,timeout:10000})}
 return <div className="trial-location-editor"><label>Nombre del negocio o dirección<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. Ferretería Beato, Villa Consuelo"/></label><button type="button" onClick={()=>setPreview(query.trim())}>Buscar ubicación</button><div className="trial-or">o</div><button type="button" onClick={current}>Usar mi ubicación actual</button>{embed&&<><iframe title="Vista previa de ubicación" src={embed}/><small>Verifica que el mapa muestre el lugar correcto.</small><button type="button" className="trial-primary" onClick={onConfirm}>Usar esta ubicación</button></>}</div>
}
export function TrialPalettePanel({onChoose}:{onChoose:(c:FreeProfileAppearanceColors)=>void}){return <div className="trial-palettes">{TRIAL_PALETTES.map(p=><button type="button" key={p.id} onClick={()=>onChoose(p.colors)}><span className="trial-swatches"><i style={{background:p.colors.primary}}/><i style={{background:p.colors.secondary}}/><i style={{background:p.colors.accent}}/></span><strong>{p.name}</strong></button>)}</div>}
export function TrialBanks({banks,editMode,onEdit}:{banks:TrialBank[];editMode:boolean;onEdit:()=>void}){if(!banks.length&&!editMode)return null;return <section className="trial-banks ilx-section"><div className="trial-bank-head"><div><small>DATOS PARA TRANSFERENCIAS</small><h2>Cuentas bancarias</h2><p>Elige una cuenta y copia los datos que necesitas para transferir.</p></div>{editMode&&<button type="button" className="ilx-live-edit" onClick={onEdit}><FaEdit/></button>}</div>{banks.map(b=><article key={b.id}><FaUniversity/><div><strong>{b.bank_name}</strong><small>{b.account_type==='checking'?'Cuenta corriente':'Cuenta de ahorros'} · {b.currency}</small><b>{b.holder_name}</b><code>{b.display_mode==='masked'&&b.account_number?'•••• '+b.account_number.slice(-4):b.account_number||'Número pendiente'}</code></div></article>)}</section>}
export function TrialBanksEditor({data,toggle,add,update}:{data:{enabled:boolean;items:TrialBank[]};toggle:(v:boolean)=>void;add:()=>void;update:(i:number,p:Partial<TrialBank>)=>void}){return <div className="trial-bank-editor"><label className="trial-module-option"><span><FaUniversity/><b>Mostrar cuentas bancarias</b></span><input type="checkbox" checked={data.enabled} onChange={e=>toggle(e.target.checked)}/></label>{data.enabled&&<>{data.items.map((b,i)=><div className="trial-bank-form" key={b.id}><label>Banco<input value={b.bank_name} onChange={e=>update(i,{bank_name:e.target.value})}/></label><label>Número de cuenta<input inputMode="numeric" value={b.account_number} onChange={e=>update(i,{account_number:e.target.value.replace(/\D/g,'')})}/></label><div className="trial-grid"><label>Tipo<select value={b.account_type} onChange={e=>update(i,{account_type:e.target.value as TrialBank['account_type']})}><option value="savings">Ahorros</option><option value="checking">Corriente</option></select></label><label>Moneda<select value={b.currency} onChange={e=>update(i,{currency:e.target.value as TrialBank['currency']})}><option>DOP</option><option>USD</option></select></label></div><label>Titular<input value={b.holder_name} onChange={e=>update(i,{holder_name:e.target.value})}/></label></div>)}{data.items.length<3&&<button type="button" className="trial-location-launch" onClick={add}><FaPlus/> Agregar cuenta</button>}</>}</div>}
export function TrialLocationButton({onClick}:{onClick:()=>void}){return <button type="button" className="trial-location-launch" onClick={onClick}><FaMapMarkerAlt/> Configurar ubicación con mapa</button>}
