import { useEffect, useMemo, useRef, useState } from 'react'
type Props={file:File;aspectRatio?:number;outputWidth?:number;onSave:(file:File)=>Promise<void>|void;onCancel:()=>void}
const W=300
const clamp=(n:number)=>Math.min(1,Math.max(0,n))
export default function TrialImageCrop({file,aspectRatio=1,outputWidth=900,onSave,onCancel}:Props){
 const H=Math.round(W/aspectRatio), outH=Math.round(outputWidth/aspectRatio), img=useRef<HTMLImageElement|null>(null), canvas=useRef<HTMLCanvasElement>(null), last=useRef<{x:number,y:number}|null>(null)
 const [ready,setReady]=useState(false),[zoom,setZoom]=useState(1),[fx,setFx]=useState(.5),[fy,setFy]=useState(.5),[busy,setBusy]=useState(false)
 useEffect(()=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{img.current=i;setReady(true)};i.src=u;return()=>URL.revokeObjectURL(u)},[file])
 const crop=useMemo(()=>{const i=img.current;if(!i||!ready)return null;const ar=aspectRatio;let bw,bh;if(i.naturalWidth/i.naturalHeight>ar){bh=i.naturalHeight;bw=bh*ar}else{bw=i.naturalWidth;bh=bw/ar}const cw=bw/zoom,ch=bh/zoom;return{x:(i.naturalWidth-cw)*fx,y:(i.naturalHeight-ch)*fy,w:cw,h:ch}},[ready,zoom,fx,fy,aspectRatio])
 useEffect(()=>{const c=canvas.current,i=img.current;if(!c||!i||!crop)return;const d=Math.min(2,window.devicePixelRatio||1);c.width=W*d;c.height=H*d;c.style.width=W+'px';c.style.height=H+'px';const g=c.getContext('2d');if(!g)return;g.setTransform(d,0,0,d,0,0);g.drawImage(i,crop.x,crop.y,crop.w,crop.h,0,0,W,H)},[crop,H])
 function move(e:React.PointerEvent<HTMLDivElement>){if(!last.current||!crop||!img.current)return;const dx=e.clientX-last.current.x,dy=e.clientY-last.current.y;last.current={x:e.clientX,y:e.clientY};const ax=Math.max(1,img.current.naturalWidth-crop.w),ay=Math.max(1,img.current.naturalHeight-crop.h);setFx(v=>clamp(v-(dx/W)*crop.w/ax));setFy(v=>clamp(v-(dy/H)*crop.h/ay))}
 async function save(){if(!img.current||!crop||busy)return;setBusy(true);const c=document.createElement('canvas');c.width=outputWidth;c.height=outH;const g=c.getContext('2d');if(!g){setBusy(false);return}g.drawImage(img.current,crop.x,crop.y,crop.w,crop.h,0,0,outputWidth,outH);const type=file.type==='image/png'?'image/png':'image/jpeg';c.toBlob(async b=>{if(!b){setBusy(false);return}try{await onSave(new File([b],file.name.replace(/\.[^.]+$/,type==='image/png'?'.png':'.jpg'),{type}))}finally{setBusy(false)}},type,type==='image/png'?undefined:.84)}
 return <div className="trial-crop-backdrop"><div className="trial-crop"><header><strong>Vista previa y encuadre</strong><button onClick={onCancel}>×</button></header><div className="trial-crop-frame" style={{width:W,height:H}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);last.current={x:e.clientX,y:e.clientY}}} onPointerMove={move} onPointerUp={()=>last.current=null}><canvas ref={canvas}/><div className="trial-crop-grid"/></div><small>Arrastra la imagen para encuadrar. Usa el control para acercar.</small><label>Zoom <input type="range" min="1" max="3" step=".01" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><b>{zoom.toFixed(1)}×</b></label><div className="trial-crop-actions"><button onClick={onCancel}>Cancelar</button><button className="trial-primary" disabled={!ready||busy} onClick={save}>{busy?'Procesando…':'Usar imagen'}</button></div></div></div>
}