-- Team permission enforcement
-- Frontend bloquea visualmente; estos triggers impiden bypass directo por API/cliente.

CREATE TRIGGER IF NOT EXISTS trg_team_profile_update_guard
BEFORE UPDATE ON profiles
WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id = OLD.id)
BEGIN
  SELECT CASE WHEN NEW.slug IS NOT OLD.slug THEN RAISE(ABORT, 'team_permission_denied:identifier') END;
  SELECT CASE WHEN NEW.name IS NOT OLD.name AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.id AND p.value='name') THEN RAISE(ABORT, 'team_permission_denied:name') END;
  SELECT CASE WHEN NEW.avatar_url IS NOT OLD.avatar_url AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.id AND p.value='photo') THEN RAISE(ABORT, 'team_permission_denied:photo') END;
  SELECT CASE WHEN json_extract(COALESCE(NEW.template_data,'{}'),'$.role') IS NOT json_extract(COALESCE(OLD.template_data,'{}'),'$.role') AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.id AND p.value='role') THEN RAISE(ABORT, 'team_permission_denied:role') END;
  SELECT CASE WHEN json_remove(COALESCE(NEW.template_data,'{}'),'$.role','$.free_identity_confirmed') IS NOT json_remove(COALESCE(OLD.template_data,'{}'),'$.role','$.free_identity_confirmed') AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.id AND p.value='design') THEN RAISE(ABORT, 'team_permission_denied:design') END;
  SELECT CASE WHEN (NEW.theme_id IS NOT OLD.theme_id OR NEW.layout_id IS NOT OLD.layout_id OR NEW.free_palette_id IS NOT OLD.free_palette_id OR NEW.free_brand_color IS NOT OLD.free_brand_color OR NEW.hero_url IS NOT OLD.hero_url OR NEW.hero_position_x IS NOT OLD.hero_position_x OR NEW.hero_position_y IS NOT OLD.hero_position_y OR NEW.hero_zoom IS NOT OLD.hero_zoom) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.id AND p.value='design') THEN RAISE(ABORT, 'team_permission_denied:design') END;
END;

CREATE TRIGGER IF NOT EXISTS trg_team_contact_update_guard
BEFORE UPDATE ON profile_contact
WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id = OLD.profile_id)
BEGIN
  SELECT CASE WHEN NEW.phone IS NOT OLD.phone AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='phone') THEN RAISE(ABORT, 'team_permission_denied:phone') END;
  SELECT CASE WHEN NEW.email IS NOT OLD.email AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='email') THEN RAISE(ABORT, 'team_permission_denied:email') END;
  SELECT CASE WHEN NEW.whatsapp IS NOT OLD.whatsapp AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='whatsapp') THEN RAISE(ABORT, 'team_permission_denied:whatsapp') END;
  SELECT CASE WHEN (NEW.address IS NOT OLD.address OR NEW.map_url IS NOT OLD.map_url) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='location') THEN RAISE(ABORT, 'team_permission_denied:location') END;
END;

CREATE TRIGGER IF NOT EXISTS trg_team_gallery_insert_guard BEFORE INSERT ON profile_gallery WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=NEW.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=NEW.profile_id AND p.value='portfolio') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:portfolio'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_gallery_update_guard BEFORE UPDATE ON profile_gallery WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='portfolio') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:portfolio'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_gallery_delete_guard BEFORE DELETE ON profile_gallery WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='portfolio') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:portfolio'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_products_insert_guard BEFORE INSERT ON profile_products WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=NEW.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=NEW.profile_id AND p.value='services') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:services'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_products_update_guard BEFORE UPDATE ON profile_products WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='services') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:services'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_products_delete_guard BEFORE DELETE ON profile_products WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='services') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:services'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_links_insert_guard BEFORE INSERT ON profile_links WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=NEW.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=NEW.profile_id AND p.value='links') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:links'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_links_update_guard BEFORE UPDATE ON profile_links WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='links') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:links'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_links_delete_guard BEFORE DELETE ON profile_links WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='links') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:links'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_social_insert_guard BEFORE INSERT ON profile_social_links WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=NEW.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=NEW.profile_id AND p.value='quick_actions') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:quick_actions'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_social_update_guard BEFORE UPDATE ON profile_social_links WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='quick_actions') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:quick_actions'); END;
CREATE TRIGGER IF NOT EXISTS trg_team_social_delete_guard BEFORE DELETE ON profile_social_links WHEN EXISTS (SELECT 1 FROM team_members tm WHERE tm.profile_id=OLD.profile_id) AND NOT EXISTS (SELECT 1 FROM team_members tm, json_each(tm.permissions_json) p WHERE tm.profile_id=OLD.profile_id AND p.value='quick_actions') BEGIN SELECT RAISE(ABORT, 'team_permission_denied:quick_actions'); END;
