import './preview-starter-apply'
import './preview-support-tickets'
import './preview-exit-feedback'
import './preview-profile-delete-mobile'
import './account-center'
import './free-profile-preview'
import './free-feedback'
import './bank-accounts'
import './preview-bank-accounts'
import './scan-status'
import './scan-to-claim'
import './ai-profile-assistant-access'
import './ai-profile-assistant'
import app from './preview-free-actions'

export default app
