import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { useParams } from 'react-router-dom'
import { FaAddressCard, FaCalendarAlt, FaClock, FaInstagram, FaMapMarkerAlt, FaWhatsapp } from 'react-icons/fa'
import SponsoredBankAccounts from './SponsoredBankAccounts'

type GalleryItem={url?:string;image_url?:string;title?:string;label?:string;description?:string}
type ScheduleItem={day?:string;days?:string;label?:string;hours?:string;time?:string}
type SponsoredData={username:string;business_name?:string;specialization?:string;what_we_do?:string;avatar_url?:string;hero_url?:string;map_url?:string;show_avatar?:boolean;phone?:string;whatsapp?:string;instagram?:string;address?:string;schedule?:ScheduleItem[];gallery?:GalleryItem[];gallery_title?:string;palette_id?:string;sponsor?:{name?:string;type?:string;logo_url?:string;banner_title?:string;banner_image_url?:string;banner_cta_label?:string;banner_cta_type?:string;banner_cta_value?:string;whatsapp_message_template?:string;website_url?:string;contact_whatsapp?:string}}

const palettes:Record<string,{accent:string;accentSoft:string;text:string}>={blue:{accent:'#174a9f',accentSoft:'#eef5ff',text:'#0f2d63'},teal:{accent:'#0f766e',accentSoft:'#ecfdf5',text:'#134e4a'},slate:{accent:'#334155',accentSoft:'#f1f5f9',text:'#0f172a'},burgundy:{accent:'#9f1239',accentSoft:'#fff1f2',text:'#881337'},gold:{accent:'#8a6423',accentSoft:'#fffbeb',text:'#65451a'}}
const RD_AREA_CODES=/^(809|829|849)/
function cleanPhone(value?:string){const input=String(value||'').trim();if(!input)return'';const hadPlus=input.startsWith('+');const digits=input.replace(/\D/g,'');if(digits.length===10&&RD_AREA_CODES.test(digits))return`+1${digits}`;if(digits.length===11&&digits.startsWith('1')&&RD_AREA_CODES.test(digits.slice(1)))return`+${digits}`;if(hadPlus&&digits.length>=7&&digits.length<=15)return`+${digits}`;return digits.length>=7&&digits.length<=15?digits:''}
function galleryUrl(item:GalleryItem){return String(item.url||item.image_url||'')}
function appOrigin(){const host=window.location.hostname.toLowerCase();if(host==='preview.intaprd.com')return'https://app.preview.intaprd.com';if(host==='intaprd.com'||host==='www.intaprd.com'||host==='link.intaprd.com')return'https://app.intaprd.com';const configured=String(import.meta.env.VITE_APP_URL||'').replace(/\/$/,'');return configured||'https://app.intaprd.com'}

export default function SponsoredProfile(){
  const{username=''}=useParams();const[data,setData]=useState<SponsoredData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[modalIndex,setModalIndex]=useState<number|null>(null);const[qrOpen,setQrOpen]=useState(false);const[qrData,setQrData]=useState('');const[toast,setToast]=useState('')
  useEffect(()=>{let alive=true;(async()=>{setLoading(true);setError('');try{const res=await fetch(`/api/v1/public/sponsored/${encodeURIComponent(username)}`);const json:any=await res.json().catch(()=>null);if(!alive)return;if(!res.ok||!json?.ok){setError(json?.error||'Perfil no disponible.');return}setData(json.data)}catch{if(alive)setError('No pudimos cargar este perfil.')}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[username])
  const gallery=useMemo(()=>Array.isArray(data?.gallery)?data!.gallery!.filter(item=>galleryUrl(item)).slice(0,10):[],[data]);const schedule=useMemo(()=>Array.isArray(data?.schedule)?data!.schedule!.slice(0,7):[],[data]);const palette=palettes[data?.palette_id||'blue']||palettes.blue;const publicUrl=typeof window!=='undefined'?window.location.href:''
useEffect(()=>{if(!toast)return;const id=window.setTimeout(()=>setToast(''),1800);return()=>window.clearTimeout(id)},[toast])
  useEffect(()=>{if(modalIndex===null)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setModalIndex(null);if(event.key==='ArrowLeft')setModalIndex(current=>current===null?null:(current-1+gallery.length)%gallery.length);if(event.key==='ArrowRight')setModalIndex(current=>current===null?null:(current+1)%gallery.length)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[modalIndex,gallery.length])
  async function share(){if(navigator.share){await navigator.share({title:data?.business_name||'KawLink',url:publicUrl}).catch(()=>undefined);return}await navigator.clipboard.writeText(publicUrl).catch(()=>undefined);setToast('Enlace copiado')}
  async function copyLink(){await navigator.clipboard.writeText(publicUrl).catch(()=>undefined);setToast('Enlace copiado')}
  async function openQr(){try{const QRCode=await import('qrcode');setQrData(await QRCode.toDataURL(publicUrl,{width:1000,margin:3,errorCorrectionLevel:'H'}));setQrOpen(true)}catch{setToast('No pudimos generar el QR')}}
  function downloadQr(){if(!qrData)return;const a=document.createElement('a');a.href=qrData;a.download=`${data?.username||'kawlink'}-qr.png`;a.click()}
  function sponsorCta(){const s=data?.sponsor;if(!s)return;let href='';if(s.banner_cta_type==='beneficiary_whatsapp'){const number=cleanPhone(data?.whatsapp||data?.phone);if(number)href=`https://wa.me/${number.replace(/^\+/,'')}?text=${encodeURIComponent(s.whatsapp_message_template||'Hola, me interesa saber más sobre estos productos.')}`}if(s.banner_cta_type==='sponsor_whatsapp'){const number=cleanPhone(s.contact_whatsapp);if(number)href=`https://wa.me/${number.replace(/^\+/,'')}?text=${encodeURIComponent(s.whatsapp_message_template||'Hola, me interesa saber más.')}`}if(s.banner_cta_type==='sponsor_url')href=String(s.banner_cta_value||s.website_url||'');if(href)window.open(href,'_blank','noopener,noreferrer')}
  if(loading)return<main style={{minHeight:'100vh',background:'#fff'}}/>;if(error||!data)return<main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,fontFamily:'Inter,system-ui,sans-serif',background:'#f8fafc'}}><div style={{maxWidth:420,textAlign:'center'}}><h1 style={{fontSize:24}}>Perfil no disponible</h1><p style={{color:'#64748b'}}>{error||'No pudimos cargar este perfil.'}</p></div></main>

  const whatsapp=cleanPhone(data.whatsapp||data.phone);const instagram=String(data.instagram||'').trim();const instagramHref=instagram?(instagram.startsWith('http')?instagram:`https://instagram.com/${instagram.replace(/^@/,'')}`):'';const mapsHref=String(data.map_url||'').trim()||(data.address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(data.address)}`:'');const vcardHref=`/api/v1/public/sponsored/${encodeURIComponent(data.username)}/vcard`
  const contactCard=(icon:ReactNode,title:string,subtitle:string,onClick:()=>void,primary=false)=><button type="button" onClick={onClick} onMouseEnter={event=>{event.currentTarget.style.transform='translateY(-2px)';event.currentTarget.style.background=primary?palette.text:palette.accentSoft;event.currentTarget.style.boxShadow=`0 10px 22px ${palette.accent}20`}} onMouseLeave={event=>{event.currentTarget.style.transform='translateY(0)';event.currentTarget.style.background=primary?palette.accent:'#fff';event.currentTarget.style.boxShadow='none'}} style={{display:'grid',gridTemplateColumns:'48px minmax(0,1fr)',alignItems:'center',minHeight:62,padding:'6px 14px 6px 7px',border:`1.5px solid ${palette.accent}`,borderRadius:999,background:primary?palette.accent:'#fff',textAlign:'center',cursor:'pointer',boxShadow:'none',minWidth:0,color:primary?'#fff':palette.text,transition:'transform .18s ease, background .18s ease, box-shadow .18s ease'}}><span style={{width:44,height:44,borderRadius:'50%',fontSize:24,color:primary?'#fff':palette.accent,display:'grid',placeItems:'center',background:primary?'rgba(255,255,255,.16)':palette.accentSoft,border:primary?'1px solid rgba(255,255,255,.18)':`1px solid ${palette.accent}22`}}>{icon}</span><span style={{minWidth:0,padding:'0 6px'}}><strong style={{display:'block',fontSize:15.5,fontWeight:900,color:primary?'#fff':palette.text,lineHeight:1.1}}>{title}</strong><small style={{display:'block',marginTop:3,fontSize:11.2,lineHeight:1.15,color:primary?'rgba(255,255,255,.82)':'#64748b',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{subtitle}</small></span></button>
  const sectionTitle:React.CSSProperties={margin:'0 0 12px',fontSize:19,lineHeight:1.2,fontWeight:800,color:palette.text,textAlign:'left'};const section:React.CSSProperties={padding:'24px 22px 0',marginTop:20,borderTop:'1px solid #e2e8f0'};const cover=`linear-gradient(135deg,${palette.accent} 0%,#0f172a 100%)`;const modalItem=modalIndex===null?null:gallery[modalIndex]

  return<main style={{minHeight:'100vh',background:'#eef2f7',fontFamily:'Inter,system-ui,sans-serif',color:'#172033'}}><article style={{width:'100%',maxWidth:520,minHeight:'100vh',margin:'0 auto',background:'#fff',boxShadow:'0 0 0 1px rgba(15,23,42,.04)',paddingBottom:30}}>
    <header style={{position:'relative'}}><div style={{height:270,background:cover,boxSizing:'border-box',overflow:'hidden',position:'relative'}}>{data.hero_url&&<img src={data.hero_url} alt="Portada" style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover'}}/>}</div>{data.show_avatar!==false&&data.avatar_url&&<img src={data.avatar_url} alt={data.business_name||'Avatar'} style={{position:'absolute',left:'50%',bottom:-54,transform:'translateX(-50%)',width:108,height:108,objectFit:'cover',borderRadius:'50%',border:'5px solid #fff',boxShadow:'0 10px 28px rgba(15,23,42,.18)',background:'#fff'}}/>}</header>
    <section style={{padding:`${data.show_avatar!==false&&data.avatar_url?78:40}px 24px 0`,textAlign:'center'}}><h1 style={{margin:0,fontSize:29,lineHeight:1.08,color:palette.text,textTransform:'uppercase',fontWeight:900}}>{data.business_name||'Nombre del negocio'}</h1><div style={{marginTop:7,fontSize:16,color:palette.accent,fontWeight:650}}>{data.specialization||'Especialización'}</div>{data.what_we_do&&<p style={{margin:'11px auto 0',maxWidth:420,color:'#5f6f86',fontSize:15,lineHeight:1.55}}>{data.what_we_do}</p>}</section>
    <section style={section}><h2 style={sectionTitle}>Contáctanos</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{contactCard(<FaWhatsapp/>,'WhatsApp','Escríbenos ahora',()=>{if(whatsapp)window.open(`https://wa.me/${whatsapp.replace(/^\+/,'')}`,'_blank')},true)}{contactCard(<FaInstagram/>,'Instagram','Síguenos',()=>{if(instagramHref)window.open(instagramHref,'_blank','noopener,noreferrer')})}{contactCard(<FaMapMarkerAlt/>,'Ubicación',data.address||'Ver ubicación',()=>{if(mapsHref)window.open(mapsHref,'_blank','noopener,noreferrer')})}{contactCard(<FaAddressCard/>,'Guardar contacto','En tu dispositivo',()=>{window.location.href=vcardHref})}</div></section>
    {schedule.length>0&&<section style={section}><div style={{border:`1px solid ${palette.accent}2f`,borderRadius:24,background:'#fff',padding:'18px 18px 16px'}}><div style={{display:'flex',alignItems:'center',justifyContent:'flex-start',gap:10,marginBottom:15}}><span style={{width:42,height:42,borderRadius:'50%',display:'grid',placeItems:'center',background:palette.accentSoft,color:palette.accent,fontSize:20}}><FaClock/></span><h2 style={{...sectionTitle,textAlign:'left',margin:0,fontSize:21,fontWeight:900}}>Nuestro horario</h2></div><div style={{display:'grid',gap:10}}>{schedule.map((item,index)=><div key={index} style={{display:'grid',gridTemplateColumns:'44px minmax(0,1fr) auto',alignItems:'center',gap:12,padding:'11px 13px',borderRadius:18,background:index%2===0?palette.accentSoft:'#fff',border:`1px solid ${palette.accent}24`}}><span style={{width:38,height:38,borderRadius:12,display:'grid',placeItems:'center',background:'#fff',color:palette.accent,fontSize:18,border:`1px solid ${palette.accent}18`}}><FaCalendarAlt/></span><strong style={{color:palette.text,fontSize:15,lineHeight:1.2,fontWeight:850}}>{item.day||item.days||item.label||'Horario'}</strong><span style={{justifySelf:'end',borderRadius:999,background:palette.accent,color:'#fff',padding:'7px 12px',fontSize:12.8,fontWeight:850,whiteSpace:'nowrap'}}>{item.hours||item.time||''}</span></div>)}</div><p style={{margin:'13px 0 0',textAlign:'center',fontSize:11.5,color:'#64748b'}}>En días especiales puede variar.</p></div></section>}
    <SponsoredBankAccounts/>
    {gallery.length>0&&<section style={section}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,marginBottom:13}}><h2 style={{...sectionTitle,margin:0}}>{data.gallery_title||'Catálogo'}</h2><span style={{color:palette.text,fontSize:12,fontWeight:800}}>{gallery.length} {gallery.length===1?'imagen':'imágenes'}</span></div><div className="sponsored-marquee" style={{overflow:'hidden',width:'100%'}}><div className="sponsored-marquee-track" style={{display:'flex',gap:10,width:'max-content'}}>{[...gallery,...gallery].map((item,index)=>{const galleryIndex=index%gallery.length;return <button key={`marquee-${index}`} type="button" onClick={()=>setModalIndex(galleryIndex)} style={{position:'relative',padding:0,border:0,borderRadius:14,overflow:'hidden',width:158,aspectRatio:'1.2/1',cursor:'pointer',background:'#fff',flex:'0 0 auto'}}><img src={galleryUrl(item)} alt={item.title||item.label||'Galería'} style={{width:'100%',height:'100%',objectFit:'cover'}}/><span style={{position:'absolute',left:0,right:0,bottom:0,padding:'17px 8px 8px',background:'linear-gradient(transparent,rgba(0,0,0,.72))',color:'#fff',fontSize:13.5,fontWeight:750,textAlign:'left'}}>{item.title||item.label||'Ver detalle'}</span></button>})}</div></div><style>{`@keyframes sponsoredGalleryMarquee{from{transform:translateX(0)}to{transform:translateX(calc(-50% - 5px))}}.sponsored-marquee-track{animation:sponsoredGalleryMarquee ${Math.max(16,gallery.length*5)}s linear infinite}.sponsored-marquee:hover .sponsored-marquee-track{animation-play-state:paused}@media (prefers-reduced-motion:reduce){.sponsored-marquee-track{animation:none}}`}</style></section>}

    <section aria-label="Acciones del perfil" style={{padding:'27px 22px 0',display:'flex',justifyContent:'center',alignItems:'center',gap:9,flexWrap:'wrap',fontSize:12.5,fontWeight:650,color:'#748399'}}><button onClick={share} style={utilityLink}>Compartir</button><span>·</span><button onClick={copyLink} style={utilityLink}>Copiar enlace</button><span>·</span><button onClick={openQr} style={utilityLink}>Descargar QR</button><span>·</span><button onClick={()=>window.location.assign(`${appOrigin()}/admin/login?resume_sponsored=1`)} style={utilityLink}>Iniciar sesión</button></section>

    <section style={{padding:'18px 22px 0'}}><div style={{textAlign:'center',fontSize:13,color:'#64748b',marginBottom:9}}>{data.sponsor?.banner_title||'Impulsado por'}: <strong style={{color:palette.text}}>{data.sponsor?.name}</strong></div>{data.sponsor?.banner_image_url?<button type="button" onClick={sponsorCta} disabled={!data.sponsor?.banner_cta_type||data.sponsor?.banner_cta_type==='none'} style={{display:'block',width:'100%',padding:0,border:0,background:'transparent',cursor:data.sponsor?.banner_cta_type==='none'?'default':'pointer'}}><img src={data.sponsor.banner_image_url} alt={data.sponsor.name||'Patrocinador'} style={{display:'block',width:'100%',height:'auto',aspectRatio:'3.2 / 1',objectFit:'contain',background:'transparent'}}/></button>:<button type="button" onClick={sponsorCta} disabled={!data.sponsor?.banner_cta_type||data.sponsor?.banner_cta_type==='none'} style={{display:'flex',width:'100%',alignItems:'center',justifyContent:'center',gap:12,padding:'12px 0',border:0,background:'transparent',cursor:data.sponsor?.banner_cta_type==='none'?'default':'pointer'}}><strong style={{color:palette.text,fontSize:16}}>{data.sponsor?.name}</strong></button>}<div style={{marginTop:10,textAlign:'center',fontSize:13,fontWeight:650,color:'#94a3b8'}}>Desarrollado por <a href="https://nfc.kawvoia.com" target="_blank" rel="noreferrer" style={{color:palette.accent,fontWeight:850,textDecoration:'underline',textUnderlineOffset:3}}>KawLink</a></div></section>
  </article>
  {modalItem&&modalIndex!==null&&<div role="dialog" aria-modal="true" aria-label="Galería completa" onClick={()=>setModalIndex(null)} style={overlay}><div onClick={e=>e.stopPropagation()} style={{width:'min(760px,100%)',background:'#fff',borderRadius:22,overflow:'hidden',position:'relative'}}><div style={{position:'relative',background:'linear-gradient(45deg,#f8fafc 25%,#eef2f7 25%,#eef2f7 50%,#f8fafc 50%,#f8fafc 75%,#eef2f7 75%)',backgroundSize:'18px 18px',minHeight:260,display:'grid',placeItems:'center'}}><img src={galleryUrl(modalItem)} alt={modalItem.title||modalItem.label||'Galería'} style={{display:'block',width:'100%',maxHeight:'72vh',objectFit:'contain'}}/>{gallery.length>1&&<><button type="button" aria-label="Imagen anterior" onClick={()=>setModalIndex((modalIndex-1+gallery.length)%gallery.length)} style={{...modalArrow,left:14}}>‹</button><button type="button" aria-label="Imagen siguiente" onClick={()=>setModalIndex((modalIndex+1)%gallery.length)} style={{...modalArrow,right:14}}>›</button></>}</div><div style={{padding:18}}><div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:16}}><div><strong style={{fontSize:18,color:palette.text}}>{modalItem.title||modalItem.label||'Detalle'}</strong>{modalItem.description&&<p style={{margin:'8px 0 0',color:'#64748b',lineHeight:1.5}}>{modalItem.description}</p>}</div><span style={{flexShrink:0,fontSize:12,fontWeight:800,color:'#64748b'}}>{modalIndex+1} de {gallery.length}</span></div>{gallery.length>1&&<div style={{display:'flex',justifyContent:'center',gap:6,marginTop:14}}>{gallery.map((_,index)=><button key={index} type="button" aria-label={`Ir a imagen ${index+1}`} onClick={()=>setModalIndex(index)} style={{border:0,padding:0,width:index===modalIndex?20:7,height:7,borderRadius:99,background:index===modalIndex?palette.accent:'#dbe4ef',cursor:'pointer'}}/>)}</div>}<button onClick={()=>setModalIndex(null)} style={{...miniBtn,width:'100%',marginTop:14}}>Cerrar</button></div></div></div>}
  {qrOpen&&<div role="dialog" aria-modal="true" onClick={()=>setQrOpen(false)} style={overlay}><div onClick={e=>e.stopPropagation()} style={{background:'#fff',borderRadius:22,padding:22,width:'min(360px,100%)',textAlign:'center'}}><h3 style={{margin:'0 0 12px'}}>QR de mi perfil</h3>{qrData&&<img src={qrData} alt="QR" style={{width:'100%',maxWidth:280}}/>}<button onClick={downloadQr} style={{...miniBtn,width:'100%',marginTop:12}}>Descargar QR</button><button onClick={()=>setQrOpen(false)} style={{...miniBtn,width:'100%',marginTop:8,background:'#fff'}}>Cerrar</button></div></div>}
  {toast&&<div style={{position:'fixed',left:'50%',bottom:24,transform:'translateX(-50%)',background:'#0f172a',color:'#fff',padding:'10px 14px',borderRadius:999,fontSize:13,zIndex:80}}>{toast}</div>}
  </main>
}

const miniBtn:React.CSSProperties={border:'1px solid #dbe4ef',background:'#f8fafc',borderRadius:12,padding:'11px 8px',fontSize:12,fontWeight:750,color:'#334155',cursor:'pointer'}
const utilityLink:React.CSSProperties={border:0,background:'transparent',padding:'3px 1px',font:'inherit',color:'#748399',cursor:'pointer',textDecoration:'none'}
const overlay:React.CSSProperties={position:'fixed',inset:0,zIndex:60,background:'rgba(15,23,42,.82)',display:'grid',placeItems:'center',padding:22}
const modalArrow:React.CSSProperties={position:'absolute',top:'50%',transform:'translateY(-50%)',width:42,height:42,borderRadius:'50%',border:'1px solid rgba(255,255,255,.28)',background:'rgba(15,23,42,.66)',color:'#fff',fontSize:30,lineHeight:1,cursor:'pointer',display:'grid',placeItems:'center'}
