import { useEffect, useState } from 'react'
import { apiGet, apiPost } from '../../lib/api'

export default function FreeDemoClaim(){
  const[ctx,setCtx]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{apiGet('/auth/free-demo-claim/context').then((j:any)=>{if(j?.ok)setCtx(j.data);else setError(j?.error||'El acceso de reclamo expiró.')}).catch(()=>setError('El acceso de reclamo expiró.'))},[])
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password!==confirm){setError('Las contraseñas no coinciden.');return}setBusy(true);try{const j:any=await apiPost('/auth/free-demo-claim/complete',{new_email:email,password});if(j?.ok)window.location.assign(j.data?.next_url||'/admin/free/credentials?claimed=1');else setError(j?.error||'No se pudo completar el reclamo.')}catch{setError('Error de conexión.')}finally{setBusy(false)}}
  return <main className="min-h-screen bg-[#f7f9fc] px-5 py-10 text-slate-950"><section className="mx-auto max-w-md rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-700">KAWVO LINK</p><h1 className="mt-3 text-2xl font-black">Haz tuya esta presentación</h1>{ctx&&<p className="mt-2 text-sm text-slate-600"><strong>{ctx.name}</strong> · /{ctx.slug}</p>}<p className="mt-4 text-sm leading-6 text-slate-600">El código ya fue validado. Define ahora tus credenciales definitivas. Al completar este paso, la presentación se desvincula del grupo Demo y pasa a ser tu perfil Free independiente.</p>{error&&<div className="mt-4 rounded-2xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>}<form onSubmit={submit} className="mt-5 space-y-3"><label className="block text-sm font-bold">Tu correo definitivo<input type="email" required className="mt-1 w-full rounded-2xl border p-3 font-normal" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@correo.com"/></label><label className="block text-sm font-bold">Nueva contraseña Kawvo<input type="password" required minLength={8} className="mt-1 w-full rounded-2xl border p-3 font-normal" value={password} onChange={e=>setPassword(e.target.value)} /></label><label className="block text-sm font-bold">Confirmar contraseña<input type="password" required minLength={8} className="mt-1 w-full rounded-2xl border p-3 font-normal" value={confirm} onChange={e=>setConfirm(e.target.value)} /></label><button disabled={busy||!ctx} className="w-full rounded-2xl bg-slate-950 px-4 py-3 font-black text-white disabled:opacity-50">{busy?'Guardando…':'Confirmar y entrar a mi perfil'}</button></form></section></main>
}
