import { useEffect, useMemo, useState } from 'react'
import { apiGet, apiPatch, apiPost } from '../../lib/api'
import SuperAdminLayout from './SuperAdminLayout'

type Sponsor={id:string;name:string;slug:string;sponsor_type:string;logo_url?:string;contact_email?:string;contact_whatsapp?:string;website_url?:string;is_active?:number;products_total?:number;products_activated?:number;profiles_published?:number}

export default function SuperAdminSponsors(){
  const [items,setItems]=useState<Sponsor[]>([]); const [selected,setSelected]=useState<Sponsor|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const [create,setCreate]=useState({name:'',slug:'',sponsor_type:'merchant',logo_url:'',contact_email:'',contact_whatsapp:'',website_url:'',owner_user_id:''})
  const [batch,setBatch]=useState({batch_name:'',public_codes:'',city:'',zone:'',notes:''})
  const [masterCode,setMasterCode]=useState('')
  const [modules,setModules]=useState({bank_accounts:false})

  async function load(){setLoading(true);setError('');try{const json:any=await apiGet('/superadmin/sponsors');if(!json?.ok)throw new Error(json?.error||'No se pudieron cargar los patrocinadores.');setItems(Array.isArray(json.data)?json.data:[])}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const totals=useMemo(()=>({sponsors:items.length,products:items.reduce((a,i)=>a+Number(i.products_total||0),0),active:items.reduce((a,i)=>a+Number(i.products_activated||0),0),published:items.reduce((a,i)=>a+Number(i.profiles_published||0),0)}),[items])

  async function createSponsor(){setSaving(true);setError('');setMessage('');try{const json:any=await apiPost('/superadmin/sponsors',create);if(!json?.ok)throw new Error(json?.error||'No se pudo crear el patrocinador.');setCreate({name:'',slug:'',sponsor_type:'merchant',logo_url:'',contact_email:'',contact_whatsapp:'',website_url:'',owner_user_id:''});setMessage('Patrocinador creado.');await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo crear.')}finally{setSaving(false)}}
  async function saveSponsor(){if(!selected)return;setSaving(true);setError('');try{const json:any=await apiPatch(`/superadmin/sponsors/${selected.id}`,selected);if(!json?.ok)throw new Error(json?.error||'No se pudo actualizar.');setMessage('Patrocinador actualizado.');await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.')}finally{setSaving(false)}}
  async function assignBatch(){if(!selected)return;const codes=batch.public_codes.split(/[\s,;]+/).map(v=>v.trim().toUpperCase()).filter(Boolean);setSaving(true);setError('');try{const json:any=await apiPost(`/superadmin/sponsors/${selected.id}/assign-artifacts`,{...batch,public_codes:codes});if(!json?.ok)throw new Error(json?.error||'No se pudo crear el lote.');setMessage(`Lote creado: ${json.data?.assigned||0} de ${json.data?.requested||codes.length} productos asignados.`);setBatch({batch_name:'',public_codes:'',city:'',zone:'',notes:''});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo crear el lote.')}finally{setSaving(false)}}
  async function assignMaster(){if(!selected||!masterCode.trim())return;setSaving(true);setError('');try{const json:any=await apiPost(`/superadmin/sponsors/${selected.id}/master-artifact`,{public_code:masterCode.trim().toUpperCase()});if(!json?.ok)throw new Error(json?.error||'No se pudo asignar el Master.');setMessage('Llavero Master asignado.');setMasterCode('')}catch(e){setError(e instanceof Error?e.message:'No se pudo asignar.')}finally{setSaving(false)}}
  async function saveModules(){if(!selected)return;setSaving(true);setError('');try{const json:any=await apiPatch(`/superadmin/sponsors/${selected.id}/modules`,{modules:[{code:'bank_accounts',enabled:modules.bank_accounts}]});if(!json?.ok)throw new Error(json?.error||'No se pudieron guardar los módulos.');setMessage('Módulos actualizados.')}catch(e){setError(e instanceof Error?e.message:'No se pudieron guardar.')}finally{setSaving(false)}}

  const input='mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold outline-none'
  const label='block text-[11px] font-black uppercase tracking-[.08em] text-slate-500'
  return <SuperAdminLayout currentSection={'sponsors' as any}><div className="space-y-5 font-['Inter'] text-slate-950"><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-cyan-600">PERFIL PATROCINADO</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Patrocinadores</h1><p className="mt-1 text-sm text-slate-500">Tenants, lotes, códigos, Master, módulos y trazabilidad del producto patrocinado.</p></div>
  {message&&<p className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{message}</p>}{error&&<p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-600">{error}</p>}
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Patrocinadores',totals.sponsors],['Productos',totals.products],['Activados',totals.active],['Perfiles publicados',totals.published]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-black uppercase tracking-[.07em] text-slate-400">{l}</p><p className="mt-2 text-3xl font-black">{v}</p></div>)}</section>
  <section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Registrar patrocinador</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className={label}>Nombre<input className={input} value={create.name} onChange={(e)=>setCreate({...create,name:e.target.value,slug:create.slug||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')})}/></label><label className={label}>Slug<input className={input} value={create.slug} onChange={(e)=>setCreate({...create,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})}/></label><label className={label}>Tipo<select className={input} value={create.sponsor_type} onChange={(e)=>setCreate({...create,sponsor_type:e.target.value})}><option value="merchant">Comercio</option><option value="brand">Marca</option></select></label><label className={label}>Usuario dueño · ID opcional<input className={input} value={create.owner_user_id} onChange={(e)=>setCreate({...create,owner_user_id:e.target.value})}/></label><label className={label}>WhatsApp<input className={input} value={create.contact_whatsapp} onChange={(e)=>setCreate({...create,contact_whatsapp:e.target.value})}/></label><label className={label}>Web<input className={input} value={create.website_url} onChange={(e)=>setCreate({...create,website_url:e.target.value})}/></label></div><button onClick={()=>void createSponsor()} disabled={saving||!create.name||!create.slug} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Crear patrocinador</button></section>
  <section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Patrocinadores registrados</h2>{loading?<p className="mt-4 text-sm text-slate-500">Cargando…</p>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map((item)=><button key={item.id} type="button" onClick={()=>setSelected({...item})} className={`rounded-2xl border p-4 text-left ${selected?.id===item.id?'border-cyan-400 bg-cyan-50':'border-slate-200 bg-white'}`}><div className="flex items-center justify-between gap-3"><div><p className="font-black">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.sponsor_type==='brand'?'Marca':'Comercio'} · {item.slug}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-black">{item.is_active===0?'Inactivo':'Activo'}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-slate-500"><span>{item.products_total||0} productos</span><span>{item.products_activated||0} activos</span><span>{item.profiles_published||0} publicados</span></div></button>)}</div>}</section>
  {selected&&<section className="grid gap-5 xl:grid-cols-2"><div className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Configuración del tenant</h2><div className="mt-4 grid gap-3"><label className={label}>Nombre<input className={input} value={selected.name||''} onChange={(e)=>setSelected({...selected,name:e.target.value})}/></label><label className={label}>Tipo<select className={input} value={selected.sponsor_type||'merchant'} onChange={(e)=>setSelected({...selected,sponsor_type:e.target.value})}><option value="merchant">Comercio</option><option value="brand">Marca</option></select></label><label className={label}>Logo · URL<input className={input} value={selected.logo_url||''} onChange={(e)=>setSelected({...selected,logo_url:e.target.value})}/></label><label className={label}>WhatsApp<input className={input} value={selected.contact_whatsapp||''} onChange={(e)=>setSelected({...selected,contact_whatsapp:e.target.value})}/></label><label className={label}>Web<input className={input} value={selected.website_url||''} onChange={(e)=>setSelected({...selected,website_url:e.target.value})}/></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={selected.is_active!==0} onChange={(e)=>setSelected({...selected,is_active:e.target.checked?1:0})}/> Patrocinador activo</label></div><button onClick={()=>void saveSponsor()} disabled={saving} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Guardar tenant</button></div>
  <div className="space-y-5"><div className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Asignar lote de productos</h2><p className="mt-1 text-sm text-slate-500">Usa códigos ya creados en Productos / códigos. Se conservan las reglas de activación existentes.</p><label className={`${label} mt-4`}>Nombre del lote<input className={input} value={batch.batch_name} onChange={(e)=>setBatch({...batch,batch_name:e.target.value})}/></label><label className={`${label} mt-3`}>Códigos<textarea className={`${input} min-h-24`} value={batch.public_codes} onChange={(e)=>setBatch({...batch,public_codes:e.target.value})} placeholder="ABC12345, DEF67890…"/></label><div className="mt-3 grid grid-cols-2 gap-3"><label className={label}>Ciudad · opcional<input className={input} value={batch.city} onChange={(e)=>setBatch({...batch,city:e.target.value})}/></label><label className={label}>Zona · opcional<input className={input} value={batch.zone} onChange={(e)=>setBatch({...batch,zone:e.target.value})}/></label></div><button onClick={()=>void assignBatch()} disabled={saving||!batch.public_codes.trim()} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Crear lote y asignar</button></div>
  <div className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Llavero Master</h2><p className="mt-1 text-sm text-slate-500">Al escanearlo con sesión del patrocinador abre su panel; no reclama perfiles.</p><input className={input} value={masterCode} onChange={(e)=>setMasterCode(e.target.value.toUpperCase())} placeholder="Código público"/><button onClick={()=>void assignMaster()} disabled={saving||!masterCode.trim()} className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black">Asignar Master</button></div>
  <div className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Módulos habilitados</h2><label className="mt-4 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={modules.bank_accounts} onChange={(e)=>setModules({...modules,bank_accounts:e.target.checked})}/> Cuentas bancarias</label><button onClick={()=>void saveModules()} disabled={saving} className="mt-4 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black">Guardar módulos</button></div></div></section>}
  </div></SuperAdminLayout>
}
