import { useEffect, useMemo, useState } from 'react'
import { apiDelete, apiGet, apiPatch, apiPost } from '../../lib/api'
import SuperAdminLayout from './SuperAdminLayout'

type Sponsor={id:string;name:string;slug?:string;profile_slug?:string;sponsor_type:string;logo_url?:string;contact_email?:string;contact_whatsapp?:string;website_url?:string;is_active?:number;products_total?:number;products_activated?:number;profiles_published?:number}
type Member={user_id:string;email?:string;name?:string;role?:string;status?:string}
type GeneratedCode={public_code:string;public_url:string}
type SponsorArtifact={public_code:string;public_url:string;product_type?:string;artifact_status?:string;status?:string;artifact_role?:string;activated_at?:string;created_at?:string;username?:string;business_name?:string;profile_status?:string;batch_name?:string;city?:string;zone?:string}

const input='mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold outline-none focus:border-cyan-400 focus:ring-4 focus:ring-cyan-100'
const label='block text-[11px] font-black uppercase tracking-[.08em] text-slate-500'
const card='rounded-[24px] border border-slate-200 bg-white p-5'

export default function SuperAdminSponsors(){
  const[items,setItems]=useState<Sponsor[]>([])
  const[selected,setSelected]=useState<Sponsor|null>(null)
  const[loading,setLoading]=useState(true)
  const[saving,setSaving]=useState(false)
  const[error,setError]=useState('')
  const[message,setMessage]=useState('')
  const[noticeScope,setNoticeScope]=useState('')
  const[create,setCreate]=useState({name:'',slug:'',sponsor_type:'merchant',logo_url:'',contact_email:'',contact_whatsapp:'',website_url:''})
  const[batch,setBatch]=useState({batch_name:'',quantity:10,product_type:'keychain',city:'',zone:'',notes:''})
  const[existingCodes,setExistingCodes]=useState('')
  const[generated,setGenerated]=useState<GeneratedCode[]>([])
  const[master,setMaster]=useState<GeneratedCode|null>(null)
  const[modules,setModules]=useState({bank_accounts:false})
  const[members,setMembers]=useState<Member[]>([])
  const[memberEmail,setMemberEmail]=useState('')
  const[memberRole,setMemberRole]=useState('admin')
  const[codes,setCodes]=useState<SponsorArtifact[]>([])
  const[codesLoading,setCodesLoading]=useState(false)
  const[codePage,setCodePage]=useState(1)
  const[codePages,setCodePages]=useState(1)
  const[codeTotal,setCodeTotal]=useState(0)
  const[codeQuery,setCodeQuery]=useState('')
  const[codeStatus,setCodeStatus]=useState('all')
  const[codeRole,setCodeRole]=useState('all')

  async function load(){setLoading(true);startNotice('load');try{const json:any=await apiGet('/superadmin/sponsors');if(!json?.ok)throw new Error(json?.error||'No se pudieron cargar los patrocinadores.');setItems(Array.isArray(json.data)?json.data:[])}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  useEffect(()=>{if(!selected){setMembers([]);setModules({bank_accounts:false});setCodes([]);setCodeTotal(0);return}Promise.all([apiGet(`/superadmin/sponsors/${selected.id}/members`),apiGet(`/superadmin/sponsors/${selected.id}/modules`)]).then(([m,g]:any[])=>{if(m?.ok)setMembers(Array.isArray(m.data)?m.data:[]);if(g?.ok){const rows=Array.isArray(g.data)?g.data:[];setModules({bank_accounts:rows.some((r:any)=>r.module_code==='bank_accounts'&&Number(r.enabled)===1)})}}).catch(()=>undefined);setGenerated([]);setMaster(null);setCodeQuery('');setCodeStatus('all');setCodeRole('all');setCodePage(1);void loadCodes(1,{q:'',status:'all',role:'all'})},[selected?.id])

  const totals=useMemo(()=>({sponsors:items.length,products:items.reduce((a,i)=>a+Number(i.products_total||0),0),active:items.reduce((a,i)=>a+Number(i.products_activated||0),0),published:items.reduce((a,i)=>a+Number(i.profiles_published||0),0)}),[items])
  async function loadCodes(page=1,filters?:{q?:string;status?:string;role?:string}){if(!selected)return;setCodesLoading(true);try{const q=filters?.q??codeQuery;const status=filters?.status??codeStatus;const role=filters?.role??codeRole;const params=new URLSearchParams({page:String(page),page_size:'10'});if(q.trim())params.set('q',q.trim());if(status!=='all')params.set('status',status);if(role!=='all')params.set('role',role);const json:any=await apiGet(`/superadmin/sponsors/${selected.id}/artifacts?${params.toString()}`);if(!json?.ok)throw new Error(json?.error||'No se pudieron cargar los códigos.');setCodes(Array.isArray(json.data)?json.data:[]);const p=json.pagination||{};setCodePage(Number(p.page||1));setCodePages(Math.max(1,Number(p.pages||1)));setCodeTotal(Number(p.total||0))}catch(e){startNotice('codes');setError(e instanceof Error?e.message:'No se pudieron cargar los códigos.')}finally{setCodesLoading(false)}}
  const startNotice=(scope:string)=>{setNoticeScope(scope);setError('');setMessage('')}
  const feedback=(scope:string)=>noticeScope===scope?<>{message&&<p className="mt-3 rounded-xl bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">{message}</p>}{error&&<p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-sm font-bold text-rose-600">{error}</p>}</>:null

  async function createSponsor(){setSaving(true);startNotice('create');try{const json:any=await apiPost('/superadmin/sponsors',create);if(!json?.ok)throw new Error(json?.error||'No se pudo crear el patrocinador.');setCreate({name:'',slug:'',sponsor_type:'merchant',logo_url:'',contact_email:'',contact_whatsapp:'',website_url:''});setMessage('Patrocinador creado. Ahora puedes generar su Master y el lote de códigos comprados.');await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo crear.')}finally{setSaving(false)}}
  async function saveSponsor(){if(!selected)return;setSaving(true);startNotice('sponsor');try{const json:any=await apiPatch(`/superadmin/sponsors/${selected.id}`,{...selected,slug:selected.profile_slug??selected.slug??''});if(!json?.ok)throw new Error(json?.error||'No se pudo actualizar.');setMessage('Patrocinador actualizado.');await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar.')}finally{setSaving(false)}}
  async function addMember(){if(!selected||!memberEmail.trim())return;setSaving(true);startNotice('member');try{const json:any=await apiPost(`/superadmin/sponsors/${selected.id}/members`,{email:memberEmail.trim().toLowerCase(),role:memberRole});if(!json?.ok)throw new Error(json?.error||'No se pudo dar acceso.');setMessage('Acceso adicional actualizado.');setMemberEmail('');const m:any=await apiGet(`/superadmin/sponsors/${selected.id}/members`);if(m?.ok)setMembers(Array.isArray(m.data)?m.data:[])}catch(e){setError(e instanceof Error?e.message:'No se pudo dar acceso.')}finally{setSaving(false)}}
  async function removeMember(userId:string){if(!selected)return;setSaving(true);startNotice('member');try{const json:any=await apiDelete(`/superadmin/sponsors/${selected.id}/members/${encodeURIComponent(userId)}`);if(!json?.ok)throw new Error(json?.error||'No se pudo retirar el acceso.');setMembers(v=>v.map(m=>m.user_id===userId?{...m,status:'inactive'}:m));setMessage('Acceso desactivado.')}catch(e){setError(e instanceof Error?e.message:'No se pudo retirar el acceso.')}finally{setSaving(false)}}
  async function generateBatch(){if(!selected)return;setSaving(true);startNotice('batch');setGenerated([]);try{const json:any=await apiPost(`/superadmin/sponsors/${selected.id}/generate-batch`,batch);if(!json?.ok)throw new Error(json?.error||'No se pudo generar el lote.');const rows=Array.isArray(json.data?.codes)?json.data.codes:[];setGenerated(rows);setMessage(`${rows.length} códigos generados y vinculados automáticamente a ${selected.name}.`);await Promise.all([load(),loadCodes(1)])}catch(e){setError(e instanceof Error?e.message:'No se pudo generar el lote.')}finally{setSaving(false)}}
  async function assignExisting(){if(!selected)return;const codes=existingCodes.split(/[\s,;]+/).map(v=>v.trim().toUpperCase()).filter(Boolean);if(!codes.length)return;setSaving(true);startNotice('existing');try{const json:any=await apiPost(`/superadmin/sponsors/${selected.id}/assign-artifacts`,{batch_name:'Códigos existentes',public_codes:codes});if(!json?.ok)throw new Error(json?.error||'No se pudieron vincular.');setExistingCodes('');setMessage(`${json.data?.assigned||0} códigos existentes vinculados.`);await Promise.all([load(),loadCodes(1)])}catch(e){setError(e instanceof Error?e.message:'No se pudieron vincular.')}finally{setSaving(false)}}
  async function generateMaster(){if(!selected)return;setSaving(true);startNotice('master');try{const json:any=await apiPost(`/superadmin/sponsors/${selected.id}/generate-master`,{});if(!json?.ok)throw new Error(json?.error||'No se pudo generar el Master.');setMaster({public_code:String(json.data?.public_code||''),public_url:String(json.data?.public_url||json.data?.activation_url||'')});setMessage(json.data?.already_exists?'Este patrocinador ya tenía un Master; te mostramos su código y URL de acceso.':'Llavero Master generado y vinculado automáticamente al patrocinador.');await Promise.all([load(),loadCodes(1)])}catch(e){setError(e instanceof Error?e.message:'No se pudo generar el Master.')}finally{setSaving(false)}}
  async function copyMasterUrl(){if(!master?.public_url)return;startNotice('master');await navigator.clipboard.writeText(master.public_url);setMessage('URL Master copiada. Esta es la URL que debes programar en el NFC/QR del Master.')}
  async function saveModules(){if(!selected)return;setSaving(true);startNotice('modules');try{const json:any=await apiPatch(`/superadmin/sponsors/${selected.id}/modules`,{modules:[{code:'bank_accounts',enabled:modules.bank_accounts}]});if(!json?.ok)throw new Error(json?.error||'No se pudieron guardar los módulos.');setMessage('Módulos actualizados.')}catch(e){setError(e instanceof Error?e.message:'No se pudieron guardar.')}finally{setSaving(false)}}
  async function copyGenerated(){if(!generated.length)return;startNotice('batch');await navigator.clipboard.writeText(generated.map(i=>`${i.public_code}\t${i.public_url}`).join('\n'));setMessage('Listado de códigos copiado. Puedes usarlo para programar los llaveros.')}

  return <SuperAdminLayout currentSection={'sponsors' as any}><div className="space-y-5 font-['Inter'] text-slate-950">
    <div><p className="text-[11px] font-black uppercase tracking-[.18em] text-cyan-600">PERFIL PATROCINADO</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Patrocinadores</h1><p className="mt-1 text-sm text-slate-500">Crea el patrocinador, genera su Master y los códigos correspondientes a la cantidad de productos comprados.</p></div>
    {feedback('load')}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Patrocinadores',totals.sponsors],['Productos',totals.products],['Activados',totals.active],['Perfiles publicados',totals.published]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-black uppercase tracking-[.07em] text-slate-400">{l}</p><p className="mt-2 text-3xl font-black">{v}</p></div>)}</section>

    <section className={card}><h2 className="text-xl font-black">Registrar patrocinador</h2><p className="mt-1 text-sm text-slate-500">El correo es el que se validará cuando el propietario active su código Master. El slug público puede dejarse vacío para que lo elija después.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className={label}>Nombre<input className={input} value={create.name} onChange={e=>setCreate({...create,name:e.target.value})}/></label><label className={label}>Slug público · opcional<input className={input} value={create.slug} onChange={e=>setCreate({...create,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})}/></label><label className={label}>Tipo<select className={input} value={create.sponsor_type} onChange={e=>setCreate({...create,sponsor_type:e.target.value})}><option value="merchant">Comercio</option><option value="brand">Marca</option></select></label><label className={label}>Correo propietario<input className={input} type="email" value={create.contact_email} onChange={e=>setCreate({...create,contact_email:e.target.value})}/></label><label className={label}>WhatsApp<input className={input} value={create.contact_whatsapp} onChange={e=>setCreate({...create,contact_whatsapp:e.target.value})}/></label><label className={label}>Web<input className={input} value={create.website_url} onChange={e=>setCreate({...create,website_url:e.target.value})}/></label></div><button onClick={()=>void createSponsor()} disabled={saving||!create.name||!create.contact_email} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Crear patrocinador</button>{feedback('create')}</section>

    <section className={card}><h2 className="text-xl font-black">Patrocinadores registrados</h2>{loading?<p className="mt-4 text-sm text-slate-500">Cargando…</p>:<div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map(item=><button key={item.id} type="button" onClick={()=>setSelected({...item})} className={`rounded-2xl border p-4 text-left ${selected?.id===item.id?'border-cyan-400 bg-cyan-50':'border-slate-200 bg-white'}`}><div className="flex items-center justify-between gap-3"><div><p className="font-black">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.sponsor_type==='brand'?'Marca':'Comercio'} · {item.contact_email||'sin correo'}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-black">{item.is_active===0?'Inactivo':'Activo'}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-slate-500"><span>{item.products_total||0} productos</span><span>{item.products_activated||0} activos</span><span>{item.profiles_published||0} publicados</span></div></button>)}</div>}</section>

    {selected&&<>
      <section className="grid gap-5 xl:grid-cols-2"><div className={card}><h2 className="text-xl font-black">Configuración del patrocinador</h2><div className="mt-4 grid gap-3"><label className={label}>Nombre<input className={input} value={selected.name||''} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label className={label}>Slug público · opcional<input className={input} value={selected.profile_slug??''} onChange={e=>setSelected({...selected,profile_slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})}/></label><label className={label}>Tipo<select className={input} value={selected.sponsor_type||'merchant'} onChange={e=>setSelected({...selected,sponsor_type:e.target.value})}><option value="merchant">Comercio</option><option value="brand">Marca</option></select></label><label className={label}>Correo propietario<input className={input} type="email" value={selected.contact_email||''} onChange={e=>setSelected({...selected,contact_email:e.target.value})}/></label><label className={label}>WhatsApp<input className={input} value={selected.contact_whatsapp||''} onChange={e=>setSelected({...selected,contact_whatsapp:e.target.value})}/></label><label className={label}>Web<input className={input} value={selected.website_url||''} onChange={e=>setSelected({...selected,website_url:e.target.value})}/></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={selected.is_active!==0} onChange={e=>setSelected({...selected,is_active:e.target.checked?1:0})}/> Patrocinador activo</label></div><button onClick={()=>void saveSponsor()} disabled={saving} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Guardar</button>{feedback('sponsor')}</div>

      <div className={card}><h2 className="text-xl font-black">Accesos adicionales</h2><p className="mt-1 text-sm leading-6 text-slate-500">El propietario no necesita agregarse aquí: se vincula cuando activa el Master con el correo registrado. Usa esta sección solo para administradores o usuarios de consulta adicionales.</p><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_150px]"><label className={label}>Correo<input className={input} type="email" value={memberEmail} onChange={e=>setMemberEmail(e.target.value)} placeholder="administrador@empresa.com"/></label><label className={label}>Rol<select className={input} value={memberRole} onChange={e=>setMemberRole(e.target.value)}><option value="admin">Administrador</option><option value="viewer">Solo lectura</option><option value="owner">Propietario adicional</option></select></label></div><button onClick={()=>void addMember()} disabled={saving||!memberEmail.trim()} className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black disabled:opacity-40">Dar acceso</button>{feedback('member')}<div className="mt-4 space-y-2">{members.length===0?<p className="text-sm text-slate-400">Todavía no hay accesos adicionales vinculados.</p>:members.map(m=><div key={m.user_id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-3 py-3"><div><p className="text-sm font-black">{m.name||m.email||m.user_id}</p><p className="text-xs text-slate-500">{m.email||''} · {m.role||'viewer'} · {m.status||'active'}</p></div>{m.status!=='inactive'&&<button type="button" onClick={()=>void removeMember(m.user_id)} className="text-xs font-black text-rose-600">Desactivar</button>}</div>)}</div></div></section>

      <section className={card}><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-black">Generar lote de códigos</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Indica la cantidad de productos comprados. El sistema genera esa cantidad de códigos nuevos y los deja vinculados inmediatamente a <strong>{selected.name}</strong>. Luego esos códigos son los que se programan en los llaveros físicos y son los mismos que verá el patrocinador en su panel.</p></div><span className="rounded-full bg-cyan-50 px-3 py-2 text-xs font-black text-cyan-800">Generación automática</span></div><div className="mt-5 grid gap-3 md:grid-cols-2"><label className={label}>Nombre del lote<input className={input} value={batch.batch_name} onChange={e=>setBatch({...batch,batch_name:e.target.value})} placeholder="Ej. Pedido septiembre · 25 unidades"/></label><label className={label}>Cantidad<input className={input} type="number" min={1} max={500} value={batch.quantity} onChange={e=>setBatch({...batch,quantity:Math.max(1,Math.min(500,Number(e.target.value)||1))})}/></label><label className={label}>Producto<select className={input} value={batch.product_type} onChange={e=>setBatch({...batch,product_type:e.target.value})}><option value="keychain">Llavero NFC/QR</option><option value="card">Tarjeta</option><option value="bracelet">Pulsera</option><option value="stand">Estación de contacto</option><option value="ping">Pin NFC</option><option value="qr">QR</option><option value="other">Otro</option></select></label><div className="grid grid-cols-2 gap-3"><label className={label}>Ciudad · opcional<input className={input} value={batch.city} onChange={e=>setBatch({...batch,city:e.target.value})}/></label><label className={label}>Zona · opcional<input className={input} value={batch.zone} onChange={e=>setBatch({...batch,zone:e.target.value})}/></label></div></div><button onClick={()=>void generateBatch()} disabled={saving||batch.quantity<1} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Generar {batch.quantity} código{batch.quantity===1?'':'s'} y vincular</button>{feedback('batch')}
      {generated.length>0&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50/50 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-black text-emerald-900">Lote generado correctamente</p><p className="text-xs text-emerald-700">Estos son los códigos que debes transferir/programar en los productos físicos.</p></div><button onClick={()=>void copyGenerated()} className="rounded-xl bg-white px-3 py-2 text-xs font-black text-emerald-800">Copiar listado</button></div><div className="mt-3 max-h-72 overflow-auto rounded-xl bg-white"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-slate-400"><tr><th className="p-3">#</th><th className="p-3">Código</th><th className="p-3">URL para NFC/QR</th></tr></thead><tbody>{generated.map((row,i)=><tr key={row.public_code} className="border-t border-slate-100"><td className="p-3">{i+1}</td><td className="p-3 font-black">{row.public_code}</td><td className="p-3 text-slate-500">{row.public_url}</td></tr>)}</tbody></table></div></div>}
      </section>

      <section className={card}>
        <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-xl font-black">Códigos del patrocinador</h2><p className="mt-1 text-sm leading-6 text-slate-500">Listado persistente de todos los códigos vinculados a <strong>{selected.name}</strong>, incluyendo lotes anteriores y el Master.</p></div><div className="text-sm font-black text-slate-500">{codeTotal} código{codeTotal===1?'':'s'}</div></div>
        <div className="mt-4 grid gap-2 md:grid-cols-[1fr_170px_170px_auto]"><input className={input} value={codeQuery} onChange={e=>setCodeQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void loadCodes(1)}} placeholder="Buscar código, lote, cliente o usuario"/><select className={input} value={codeStatus} onChange={e=>{const v=e.target.value;setCodeStatus(v);void loadCodes(1,{status:v})}}><option value="all">Todos los estados</option><option value="available">Pendientes</option><option value="activated">Activados</option><option value="inactive">Inactivos</option></select><select className={input} value={codeRole} onChange={e=>{const v=e.target.value;setCodeRole(v);void loadCodes(1,{role:v})}}><option value="all">Todos los tipos</option><option value="beneficiary">Beneficiarios</option><option value="master">Master</option></select><button type="button" onClick={()=>void loadCodes(1)} className="mt-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white">Buscar</button></div>
        {feedback('codes')}
        <div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50 text-slate-400"><tr><th className="p-3">#</th><th className="p-3">Código / URL</th><th className="p-3">Producto</th><th className="p-3">Tipo</th><th className="p-3">Estado</th><th className="p-3">Cliente / perfil</th><th className="p-3">Lote / zona</th></tr></thead><tbody>{codesLoading?<tr><td colSpan={7} className="p-6 text-center text-slate-400">Cargando códigos…</td></tr>:codes.length===0?<tr><td colSpan={7} className="p-6 text-center text-slate-400">No hay códigos que coincidan con este filtro.</td></tr>:codes.map((row,i)=><tr key={row.public_code} className="border-t border-slate-100 align-top"><td className="p-3 text-slate-400">{(codePage-1)*10+i+1}</td><td className="p-3"><div className="font-black text-slate-900">{row.public_code}</div><a href={row.public_url} target="_blank" rel="noreferrer" className="mt-1 block max-w-[300px] break-all font-semibold text-cyan-700 underline">{row.public_url}</a></td><td className="p-3">{row.product_type||'—'}</td><td className="p-3"><span className={`rounded-full px-2 py-1 font-black ${row.artifact_role==='master'?'bg-violet-50 text-violet-700':'bg-slate-100 text-slate-600'}`}>{row.artifact_role==='master'?'Master':'Beneficiario'}</span></td><td className="p-3"><span className={`rounded-full px-2 py-1 font-black ${row.status==='activated'?'bg-emerald-50 text-emerald-700':row.status==='inactive'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{row.status==='activated'?'Activado':row.status==='inactive'?'Inactivo':'Pendiente'}</span></td><td className="p-3"><div className="font-bold text-slate-700">{row.business_name||'—'}</div><div className="mt-1 text-slate-400">{row.username?`/p/${row.username}`:row.profile_status||'Sin perfil'}</div></td><td className="p-3"><div>{row.batch_name||'—'}</div><div className="mt-1 text-slate-400">{[row.city,row.zone].filter(Boolean).join(' · ')||'—'}</div></td></tr>)}</tbody></table></div>
        <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs font-semibold text-slate-500">Página {codePage} de {codePages} · {codeTotal} registros</p><div className="flex gap-2"><button type="button" onClick={()=>void loadCodes(codePage-1)} disabled={codesLoading||codePage<=1} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black disabled:opacity-35">← Anterior</button><button type="button" onClick={()=>void loadCodes(codePage+1)} disabled={codesLoading||codePage>=codePages} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black disabled:opacity-35">Siguiente →</button></div></div>
      </section>

      <section className="grid gap-5 xl:grid-cols-2"><div className={card}><h2 className="text-xl font-black">Llavero Master</h2><p className="mt-1 text-sm leading-6 text-slate-500">Genera el código principal del patrocinador. La URL Master es la que debes programar en el NFC/QR. Al abrirla, el sistema reconoce al patrocinador, valida el correo propietario y continúa con acceso/activación hacia su perfil patrocinado y panel.</p><button onClick={()=>void generateMaster()} disabled={saving} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">Generar código Master</button>{master&&<div className="mt-4 rounded-2xl bg-cyan-50 p-4"><p className="text-[11px] font-black uppercase tracking-[.08em] text-cyan-700">Código Master</p><p className="mt-2 text-2xl font-black tracking-wider">{master.public_code}</p><p className="mt-4 text-[11px] font-black uppercase tracking-[.08em] text-cyan-700">URL Master · acceso y activación</p><a href={master.public_url} target="_blank" rel="noreferrer" className="mt-2 block break-all text-sm font-bold text-cyan-900 underline">{master.public_url}</a><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>void copyMasterUrl()} className="rounded-xl bg-white px-3 py-2 text-xs font-black text-cyan-900">Copiar URL Master</button><button type="button" onClick={()=>window.open(master.public_url,'_blank','noopener,noreferrer')} className="rounded-xl border border-cyan-200 bg-transparent px-3 py-2 text-xs font-black text-cyan-900">Probar acceso</button></div>{feedback('master')}<p className="mt-3 text-xs leading-5 text-cyan-800">Programa la URL completa en el llavero Master. No programes solamente el código.</p></div>}{!master&&feedback('master')}</div>
      <div className={card}><h2 className="text-xl font-black">Módulos habilitados</h2><label className="mt-4 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={modules.bank_accounts} onChange={e=>setModules({...modules,bank_accounts:e.target.checked})}/> Cuentas bancarias · máximo 3 activas</label><button onClick={()=>void saveModules()} disabled={saving} className="mt-4 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black">Guardar módulos</button>{feedback('modules')}</div></section>

      <section className={card}><details><summary className="cursor-pointer text-sm font-black text-slate-700">Vincular códigos existentes manualmente</summary><p className="mt-2 text-sm text-slate-500">Solo para códigos que ya fueron creados anteriormente en Productos/códigos y todavía están libres. Para compras nuevas usa “Generar lote de códigos”.</p><textarea className={`${input} mt-3 min-h-24`} value={existingCodes} onChange={e=>setExistingCodes(e.target.value)} placeholder="ABC12345, DEF67890…"/><button onClick={()=>void assignExisting()} disabled={saving||!existingCodes.trim()} className="mt-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-black disabled:opacity-40">Vincular existentes</button>{feedback('existing')}</details></section>
    </>}
  </div></SuperAdminLayout>
}
