import { useEffect, useMemo, useState } from 'react'
import { API_BASE, apiGet, apiPatch } from '../../../lib/api'

export default function SponsorDashboard(){
  const[tenant,setTenant]=useState<any>(null);const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('')
  const[form,setForm]=useState<any>({logo_url:'',banner_title:'Impulsado por',banner_image_url:'',banner_cta_label:'Conocer más',banner_cta_type:'beneficiary_whatsapp',banner_cta_value:'',whatsapp_message_template:'Hola, me interesa saber más sobre estos productos.',contact_whatsapp:'',website_url:''})
  async function load(){setLoading(true);setError('');try{const[me,list]:any[]=await Promise.all([apiGet('/sponsor/me'),apiGet('/sponsor/artifacts')]);if(!me?.ok)throw new Error(me?.error||'No pudimos abrir el patrocinador.');setTenant(me.data);if(me.data)setForm((v:any)=>({...v,...me.data}));if(list?.ok)setItems(Array.isArray(list.data)?list.data:[])}catch(e){setError(e instanceof Error?e.message:'No pudimos abrir el patrocinador.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const stats=useMemo(()=>({total:items.filter(i=>i.artifact_role!=='master').length,active:items.filter(i=>i.artifact_role!=='master'&&i.status==='activated').length,pending:items.filter(i=>i.artifact_role!=='master'&&i.status==='available').length,published:items.filter(i=>i.profile_status==='published').length}),[items])
  async function upload(file:File|undefined,kind:'logo'|'banner'){if(!file)return;setUploading(kind);setError('');try{const fd=new FormData();fd.append('file',file);const res=await fetch(`${API_BASE}/sponsor/media?kind=${kind}`,{method:'POST',credentials:'include',body:fd});const json:any=await res.json().catch(()=>null);if(!res.ok||!json?.ok)throw new Error(json?.error||'No pudimos subir la imagen.');setForm((v:any)=>({...v,[kind==='logo'?'logo_url':'banner_image_url']:json.url}))}catch(e){setError(e instanceof Error?e.message:'No pudimos subir la imagen.')}finally{setUploading('')}}
  async function save(){setSaving(true);setMessage('');setError('');try{const json:any=await apiPatch('/sponsor/settings',form);if(!json?.ok)throw new Error(json?.error||'No pudimos guardar el patrocinio.');setMessage('Patrocinio actualizado en todos los perfiles asociados.');await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar.')}finally{setSaving(false)}}
  if(loading)return<main className="min-h-screen bg-[#f7f9fc]"/>;if(!tenant)return<main className="min-h-screen bg-[#f7f9fc] px-5 py-10 font-['Inter']"><div className="mx-auto max-w-xl rounded-3xl border border-slate-200 bg-white p-6"><h1 className="text-2xl font-black">Panel patrocinador</h1><p className="mt-2 text-slate-500">{error||'Tu cuenta no tiene un módulo de patrocinio activo.'}</p></div></main>
  const input='mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none focus:border-cyan-400 focus:ring-4 focus:ring-cyan-100';const label='block text-xs font-black uppercase tracking-[.08em] text-slate-500'
  return<main className="min-h-screen bg-[#f7f9fc] px-4 py-7 font-['Inter'] text-slate-950"><div className="mx-auto max-w-[1000px] space-y-5"><header className="rounded-[28px] border border-slate-200 bg-white p-6"><p className="text-[11px] font-black uppercase tracking-[.18em] text-cyan-600">MÓDULO PATROCINIO</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">{tenant.name}</h1><p className="mt-1 text-sm text-slate-500">Gestiona tu imagen patrocinada y la trazabilidad de tus productos.</p></header>
  {message&&<p className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{message}</p>}{error&&<p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-600">{error}</p>}
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Comprados',stats.total],['Activos',stats.active],['Pendientes',stats.pending],['Publicados',stats.published]].map(([labelText,value])=><div key={String(labelText)} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-black uppercase tracking-[.08em] text-slate-400">{labelText}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</section>
  <section className="rounded-[26px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Panel de cintillo patrocinado</h2><p className="mt-1 text-sm text-slate-500">Un cambio aquí se refleja centralmente en todos tus perfiles patrocinados.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">
    <label className={label}>Logo<input type="file" accept="image/jpeg,image/png,image/webp" className={input} onChange={e=>void upload(e.target.files?.[0],'logo')}/><span className="mt-2 block text-[11px] normal-case tracking-normal text-slate-400">{uploading==='logo'?'Subiendo…':form.logo_url?'Logo cargado':'JPG, PNG o WEBP · máximo 8 MB'}</span></label>
    <label className={label}>Título sobre el banner<input className={input} value={form.banner_title||''} onChange={e=>setForm({...form,banner_title:e.target.value})}/></label>
    <label className={`${label} sm:col-span-2`}>Imagen del banner<input type="file" accept="image/jpeg,image/png,image/webp" className={input} onChange={e=>void upload(e.target.files?.[0],'banner')}/><span className="mt-2 block text-[11px] normal-case tracking-normal text-slate-400">{uploading==='banner'?'Subiendo…':form.banner_image_url?'Banner cargado':'JPG, PNG o WEBP · máximo 8 MB'}</span>{form.banner_image_url&&<img src={form.banner_image_url} alt="Vista previa del banner" className="mt-3 h-32 w-full rounded-2xl object-cover"/>}</label>
    <label className={label}>Texto CTA<input className={input} value={form.banner_cta_label||''} onChange={e=>setForm({...form,banner_cta_label:e.target.value})}/></label><label className={label}>Destino CTA<select className={input} value={form.banner_cta_type||'none'} onChange={e=>setForm({...form,banner_cta_type:e.target.value})}><option value="beneficiary_whatsapp">WhatsApp del beneficiario</option><option value="sponsor_whatsapp">WhatsApp del patrocinador</option><option value="sponsor_url">Enlace del patrocinador</option><option value="none">Sin CTA</option></select></label>
    <label className={label}>WhatsApp patrocinador<input className={input} value={form.contact_whatsapp||''} onChange={e=>setForm({...form,contact_whatsapp:e.target.value})}/></label><label className={label}>Web / enlace comercial<input className={input} value={form.website_url||''} onChange={e=>setForm({...form,website_url:e.target.value})}/></label><label className={`${label} sm:col-span-2`}>Mensaje precargado<textarea className={`${input} min-h-20`} maxLength={240} value={form.whatsapp_message_template||''} onChange={e=>setForm({...form,whatsapp_message_template:e.target.value})}/></label>
  </div><button onClick={()=>void save()} disabled={saving||Boolean(uploading)} className="mt-5 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{saving?'Guardando…':'Guardar patrocinio'}</button></section>
  <section className="rounded-[26px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Trazabilidad</h2><p className="mt-1 text-sm text-slate-500">Códigos comprados, activaciones y cliente asociado. Ciudad y zona aparecen solo cuando el lote las usa.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-[.08em] text-slate-400"><th className="py-3 pr-3">Código</th><th className="py-3 pr-3">Producto</th><th className="py-3 pr-3">Estado</th><th className="py-3 pr-3">Cliente</th><th className="py-3 pr-3">Perfil</th><th className="py-3">Lote / zona</th></tr></thead><tbody>{items.map(item=><tr key={item.public_code} className="border-b border-slate-100"><td className="py-3 pr-3 font-black">{item.public_code}</td><td className="py-3 pr-3">{item.artifact_role==='master'?'Llavero Master':item.product_type}</td><td className="py-3 pr-3">{item.status}</td><td className="py-3 pr-3">{item.business_name||'—'}</td><td className="py-3 pr-3">{item.username?`/p/${item.username}`:item.profile_status||'—'}</td><td className="py-3">{[item.batch_name,item.city,item.zone].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table></div></section>
  </div></main>
}
