import { useEffect, useState } from 'react'
import { apiDelete, apiGet, apiPatch, apiPost } from '../../../lib/api'

type Bank={id:string;bank_name:string;account_number:string;account_type:'savings'|'checking';currency:'DOP'|'USD';holder_name:string;sort_order:number}
const MAX_ACTIVE=3
const blank={bank_name:'',account_number:'',account_type:'savings',currency:'DOP',holder_name:''}

export function SponsoredBankModuleLauncher(){
  const[enabled,setEnabled]=useState(false)
  useEffect(()=>{apiGet('/me/sponsored-profile/bank-accounts').then((j:any)=>setEnabled(Boolean(j?.ok&&j?.data?.enabled))).catch(()=>undefined)},[])
  if(!enabled)return null
  return <a href="/admin/sponsored/bank-accounts" className="fixed bottom-5 right-5 z-40 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-black text-white shadow-xl no-underline">Configurar cuentas</a>
}

export default function SponsoredBankAccounts(){
  const[enabled,setEnabled]=useState(false);const[items,setItems]=useState<Bank[]>([]);const[form,setForm]=useState<any>(blank);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('')
  async function load(){setError('');try{const j:any=await apiGet('/me/sponsored-profile/bank-accounts');if(!j?.ok)throw new Error(j?.error||'No pudimos cargar las cuentas.');setEnabled(Boolean(j.data?.enabled));setItems(Array.isArray(j.data?.items)?j.data.items:[])}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar las cuentas.')}}
  useEffect(()=>{void load()},[])
  async function add(){setSaving(true);setError('');setMessage('');try{const j:any=await apiPost('/me/sponsored-profile/bank-accounts',form);if(!j?.ok)throw new Error(j?.error||'No pudimos agregar la cuenta.');setForm(blank);setMessage('Cuenta agregada.');await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos agregar la cuenta.')}finally{setSaving(false)}}
  async function update(item:Bank){setSaving(true);setError('');try{const j:any=await apiPatch(`/me/sponsored-profile/bank-accounts/${item.id}`,item);if(!j?.ok)throw new Error(j?.error||'No pudimos guardar.');setMessage('Cuenta actualizada.');await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar.')}finally{setSaving(false)}}
  async function remove(id:string){setSaving(true);setError('');try{const j:any=await apiDelete(`/me/sponsored-profile/bank-accounts/${id}`);if(!j?.ok)throw new Error(j?.error||'No pudimos quitar la cuenta.');setMessage('Cuenta eliminada.');await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos quitar la cuenta.')}finally{setSaving(false)}}
  const input='mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none focus:border-cyan-400';const label='block text-xs font-black uppercase tracking-[.08em] text-slate-500'
  return <main className="min-h-screen bg-[#f7f9fc] px-4 py-7 font-['Inter'] text-slate-950"><div className="mx-auto max-w-[820px] space-y-5"><header className="rounded-[28px] border border-slate-200 bg-white p-5"><a href="/admin/sponsored" className="text-xs font-black text-cyan-700 no-underline">← Mi presentación</a><h1 className="mt-3 text-3xl font-black tracking-[-.04em]">Configurar cuentas bancarias</h1><p className="mt-2 text-sm text-slate-500">Este módulo aparece en tu panel únicamente cuando ha sido habilitado para tu patrocinio. Puedes mantener hasta 3 cuentas activas.</p></header>{message&&<p className="rounded-2xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{message}</p>}{error&&<p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-600">{error}</p>}
  {!enabled?<section className="rounded-[26px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Módulo no habilitado</h2><p className="mt-2 text-sm text-slate-500">Esta función no forma parte de tu patrocinio actual.</p></section>:<><section className="rounded-[26px] border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Agregar cuenta</h2><p className="mt-1 text-sm text-slate-500">Máximo 3 cuentas bancarias activas por perfil.</p></div><span className="text-xs font-black text-slate-400">{items.length}/{MAX_ACTIVE}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className={label}>Banco<input className={input} value={form.bank_name} onChange={e=>setForm({...form,bank_name:e.target.value})}/></label><label className={label}>Número de cuenta<input className={input} value={form.account_number} onChange={e=>setForm({...form,account_number:e.target.value})}/></label><label className={label}>Titular<input className={input} value={form.holder_name} onChange={e=>setForm({...form,holder_name:e.target.value})}/></label><label className={label}>Tipo<select className={input} value={form.account_type} onChange={e=>setForm({...form,account_type:e.target.value})}><option value="savings">Ahorros</option><option value="checking">Corriente</option></select></label><label className={label}>Moneda<select className={input} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option value="DOP">DOP</option><option value="USD">USD</option></select></label></div><button disabled={saving||items.length>=MAX_ACTIVE||!form.bank_name||!form.account_number||!form.holder_name} onClick={()=>void add()} className="mt-4 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-black text-white disabled:opacity-40">{items.length>=MAX_ACTIVE?'Límite de 3 cuentas alcanzado':'Agregar cuenta'}</button></section>
  <section className="rounded-[26px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Mis cuentas</h2><div className="mt-4 space-y-3">{items.length===0?<p className="text-sm text-slate-400">Todavía no has agregado cuentas.</p>:items.map((item,index)=><div key={item.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><label className={label}>Banco<input className={input} value={item.bank_name} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,bank_name:e.target.value}:x))}/></label><label className={label}>Número<input className={input} value={item.account_number} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,account_number:e.target.value}:x))}/></label><label className={label}>Titular<input className={input} value={item.holder_name} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,holder_name:e.target.value}:x))}/></label><label className={label}>Tipo<select className={input} value={item.account_type} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,account_type:e.target.value as Bank['account_type']}:x))}><option value="savings">Ahorros</option><option value="checking">Corriente</option></select></label><label className={label}>Moneda<select className={input} value={item.currency} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,currency:e.target.value as Bank['currency']}:x))}><option value="DOP">DOP</option><option value="USD">USD</option></select></label></div><div className="mt-3 flex gap-2"><button disabled={saving} onClick={()=>void update({...item,sort_order:index})} className="rounded-xl bg-slate-950 px-4 py-2 text-xs font-black text-white">Guardar</button><button disabled={saving} onClick={()=>void remove(item.id)} className="rounded-xl border border-rose-200 px-4 py-2 text-xs font-black text-rose-600">Quitar</button></div></div>)}</div></section></>}
  </div></main>
}
