import { useEffect, useMemo, useState } from 'react'
import { apiDelete, apiGet, apiPatch, apiPost, apiPut } from '../../../lib/api'

type HolderIdType='cedula'|'rnc'
type Bank={id:string;bank_code:string|null;bank_name:string;account_number:string;display_number:string;account_type:'savings'|'checking';currency:'DOP'|'USD';holder_name:string;holder_id_type:HolderIdType|null;holder_id_number:string;display_mode:'masked'|'visible';sort_order:number}
const MAX_ACTIVE=3
const BANKS=[
  {code:'vimenca',name:'Banco Vimenca'},{code:'promerica',name:'Banco Promerica'},{code:'popular',name:'Banco Popular Dominicano'},{code:'bdi',name:'Banco BDI'},{code:'santa-cruz',name:'Banco Santa Cruz'},{code:'bhd-leon',name:'Banco BHD León'},{code:'ademi',name:'Banco Ademi'},{code:'banesco',name:'Banesco'},{code:'scotiabank',name:'Scotiabank República Dominicana'},{code:'la-nacional',name:'La Nacional Ahorros y Préstamos'},{code:'banreservas',name:'Banco de Reservas'},{code:'citi',name:'Citi'},{code:'caribe',name:'Banco Caribe'},{code:'lopez-de-haro',name:'Banco López de Haro'},{code:'bellbank',name:'Bellbank'},{code:'activo-dominicana',name:'Banco Múltiple Activo Dominicana'},{code:'lafise',name:'Banco LAFISE'},{code:'asociacion-cibao',name:'Asociación Cibao de Ahorros y Préstamos'},{code:'otro',name:'Otro banco'},
]
const blank={bank_code:'popular',bank_name:'Banco Popular Dominicano',account_number:'',account_type:'savings' as const,currency:'DOP' as const,holder_name:'',holder_id_type:'cedula' as HolderIdType,holder_id_number:'',display_mode:'masked' as const}

function bankInitials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')||'B'}

export function SponsoredBankAccountsSection({mode='beneficiary',profileId}:{mode?:'beneficiary'|'master';profileId?:string}={}){
  const params=new URLSearchParams();if(mode==='master')params.set('scope','master');else if(profileId)params.set('profile_id',profileId);const scopeQuery=params.toString()?`?${params.toString()}`:''
  const[allowed,setAllowed]=useState(false)
  const[enabled,setEnabled]=useState(true)
  const[items,setItems]=useState<Bank[]>([])
  const[form,setForm]=useState<any>(blank)
  const[editingId,setEditingId]=useState<string|null>(null)
  const[saving,setSaving]=useState(false)
  const[loading,setLoading]=useState(true)
  const[error,setError]=useState('')
  const[message,setMessage]=useState('')
  const remaining=useMemo(()=>Math.max(0,MAX_ACTIVE-items.length),[items.length])
  async function load(){setLoading(true);setError('');try{const j:any=await apiGet(`/me/sponsored-profile/bank-accounts${scopeQuery}`);if(!j?.ok)throw new Error(j?.error||'No pudimos cargar las cuentas.');setAllowed(Boolean(j.data?.access?.allowed));setEnabled(j.data?.enabled!==false);setItems(Array.isArray(j.data?.items)?j.data.items:[])}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar las cuentas.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[scopeQuery])
  function selectBank(code:string){const bank=BANKS.find(item=>item.code===code)||BANKS[0];setForm((current:any)=>({...current,bank_code:bank.code,bank_name:bank.name}))}
  function reset(){setEditingId(null);setForm(blank)}
  function startEdit(item:Bank){setEditingId(item.id);setForm({...item,bank_code:item.bank_code||'otro',holder_id_type:item.holder_id_type||'cedula',holder_id_number:item.holder_id_number||'',display_mode:item.display_mode||'masked'});document.getElementById('sponsored-bank-accounts')?.scrollIntoView({behavior:'smooth',block:'start'})}
  async function save(){if(saving)return;setError('');setMessage('');const idDigits=String(form.holder_id_number||'').replace(/\D/g,'');if(!form.bank_name.trim()||String(form.account_number||'').replace(/\s+/g,'').length<4||!form.holder_name.trim()||!form.holder_id_type||idDigits.length<9){setError('Completa banco, número de cuenta, titular y Cédula/RNC.');return}setSaving(true);try{const payload={...form,account_number:String(form.account_number||'').replace(/\s+/g,''),holder_id_number:idDigits};const j:any=editingId?await apiPatch(`/me/sponsored-profile/bank-accounts/${editingId}${scopeQuery}`,payload):await apiPost(`/me/sponsored-profile/bank-accounts${scopeQuery}`,payload);if(!j?.ok)throw new Error(j?.error||'No pudimos guardar la cuenta.');setMessage(editingId?'Cuenta actualizada.':'Cuenta agregada.');reset();await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar la cuenta.')}finally{setSaving(false)}}
  async function toggleSection(){if(!allowed||saving)return;setSaving(true);setError('');setMessage('');const next=!enabled;try{const j:any=await apiPut(`/me/sponsored-profile/bank-accounts/settings${scopeQuery}`,{enabled:next});if(!j?.ok)throw new Error(j?.error||'No pudimos cambiar la visibilidad.');setEnabled(next);setMessage(next?'Sección visible en tu perfil.':'Sección oculta en tu perfil.')}catch(e){setError(e instanceof Error?e.message:'No pudimos cambiar la visibilidad.')}finally{setSaving(false)}}
  async function remove(id:string){if(saving||!window.confirm('¿Eliminar esta cuenta bancaria?'))return;setSaving(true);setError('');setMessage('');try{const j:any=await apiDelete(`/me/sponsored-profile/bank-accounts/${id}${scopeQuery}`);if(!j?.ok)throw new Error(j?.error||'No pudimos eliminar la cuenta.');if(editingId===id)reset();setMessage('Cuenta eliminada.');await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos eliminar la cuenta.')}finally{setSaving(false)}}
  if(loading)return <section id="sponsored-bank-accounts" data-sponsored-tour="bank-accounts" className="rounded-[26px] border border-slate-200 bg-white p-5"><p className="text-sm font-semibold text-slate-400">Cargando cuentas bancarias…</p></section>
  if(!allowed)return null
  return <section id="sponsored-bank-accounts" data-sponsored-tour="bank-accounts" className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-[0_12px_35px_rgba(15,23,42,.04)]">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.12em] text-cyan-700">Cuentas bancarias</p><h2 className="mt-1 text-xl font-black">Facilita las transferencias bancarias</h2><p className="mt-1 text-sm leading-6 text-slate-500">Agrega hasta 3 cuentas para que tus clientes copien los datos necesarios desde tu perfil.</p></div><span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700">{items.length}/{MAX_ACTIVE}</span></div>
    <div className="mt-5 flex items-center justify-between gap-4 rounded-[22px] border border-slate-200 bg-slate-50 p-4"><div><p className="text-sm font-black">Mostrar en mi perfil</p><p className="mt-1 text-xs font-medium text-slate-500">Puedes ocultar toda la sección sin borrar tus cuentas.</p></div><button type="button" onClick={()=>void toggleSection()} disabled={saving} aria-pressed={enabled} className={`relative h-8 w-14 shrink-0 rounded-full transition ${enabled?'bg-cyan-600':'bg-slate-200'}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white shadow transition ${enabled?'left-7':'left-1'}`}/></button></div>
    {(error||message)&&<p className={`mt-4 rounded-2xl px-4 py-3 text-sm font-black ${error?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{error||message}</p>}
    {(items.length<MAX_ACTIVE||editingId)&&<div className="mt-5 rounded-[24px] border border-slate-200 bg-slate-50/60 p-4">
      <div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.1em] text-slate-400">{editingId?'Editar cuenta':'Agregar cuenta'}</p><p className="mt-1 text-lg font-black">{editingId?'Actualiza los datos':`${remaining} ${remaining===1?'espacio disponible':'espacios disponibles'}`}</p></div>{editingId&&<button type="button" onClick={reset} className="rounded-xl bg-white px-3 py-2 text-xs font-black text-slate-600">Cancelar</button>}</div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <label className="block sm:col-span-2"><span className="text-sm font-black text-slate-700">Banco</span><select value={form.bank_code} onChange={e=>selectBank(e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 font-semibold">{BANKS.map(bank=><option key={bank.code} value={bank.code}>{bank.name}</option>)}</select></label>
        {form.bank_code==='otro'&&<label className="block sm:col-span-2"><span className="text-sm font-black text-slate-700">Nombre del banco</span><input value={form.bank_name||''} onChange={e=>setForm({...form,bank_name:e.target.value})} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5"/></label>}
        <label className="block sm:col-span-2"><span className="text-sm font-black text-slate-700">Número de cuenta</span><input value={form.account_number||''} onChange={e=>setForm({...form,account_number:e.target.value.replace(/[^0-9A-Za-z ]/g,'')})} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 font-semibold tracking-wide outline-none focus:border-cyan-400"/></label>
        <label className="block"><span className="text-sm font-black text-slate-700">Tipo de cuenta</span><select value={form.account_type} onChange={e=>setForm({...form,account_type:e.target.value})} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 font-semibold"><option value="savings">Ahorros</option><option value="checking">Corriente</option></select></label>
        <label className="block"><span className="text-sm font-black text-slate-700">Moneda</span><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 font-semibold"><option value="DOP">Peso dominicano (DOP)</option><option value="USD">Dólar (USD)</option></select></label>
        <label className="block sm:col-span-2"><span className="text-sm font-black text-slate-700">Titular</span><input value={form.holder_name||''} onChange={e=>setForm({...form,holder_name:e.target.value})} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 outline-none focus:border-cyan-400"/></label>
        <label className="block"><span className="text-sm font-black text-slate-700">Identificación del titular</span><select value={form.holder_id_type} onChange={e=>setForm({...form,holder_id_type:e.target.value,holder_id_number:''})} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 font-semibold"><option value="cedula">Cédula</option><option value="rnc">RNC</option></select></label>
        <label className="block"><span className="text-sm font-black text-slate-700">Número de {form.holder_id_type==='rnc'?'RNC':'cédula'}</span><input value={form.holder_id_number||''} onChange={e=>setForm({...form,holder_id_number:e.target.value.replace(/\D/g,'')})} inputMode="numeric" autoComplete="off" placeholder="Solo números" className="mt-2 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 font-semibold tracking-wide"/></label>
        <p className="sm:col-span-2 rounded-xl bg-white px-3 py-2 text-xs font-semibold leading-5 text-slate-500">La Cédula/RNC no se mostrará públicamente. El visitante solo tendrá la opción de copiarla cuando la necesite.</p>
        <div className="sm:col-span-2"><p className="text-sm font-black text-slate-700">Cómo mostrar el número de cuenta</p><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setForm({...form,display_mode:'masked'})} className={`rounded-2xl border p-3 text-left ${form.display_mode==='masked'?'border-cyan-500 bg-cyan-50 ring-4 ring-cyan-100':'border-slate-200 bg-white'}`}><span className="block text-sm font-black">Oculto</span><span className="mt-1 block text-xs text-slate-500">XXXX XXXX 0236</span></button><button type="button" onClick={()=>setForm({...form,display_mode:'visible'})} className={`rounded-2xl border p-3 text-left ${form.display_mode==='visible'?'border-cyan-500 bg-cyan-50 ring-4 ring-cyan-100':'border-slate-200 bg-white'}`}><span className="block text-sm font-black">Visible</span><span className="mt-1 block text-xs text-slate-500">Número completo</span></button></div></div>
      </div>
      <button type="button" onClick={()=>void save()} disabled={saving} className="mt-4 w-full rounded-2xl bg-slate-950 px-4 py-4 text-sm font-black text-white disabled:opacity-40">{saving?'Guardando…':editingId?'Guardar cambios':'Agregar cuenta'}</button>
    </div>}
    <div className="mt-5 space-y-3">{items.length===0?<div className="rounded-[22px] border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><p className="font-black text-slate-700">Todavía no has agregado cuentas</p><p className="mt-1 text-sm text-slate-500">Cuando agregues una, aparecerá aquí y en tu perfil público.</p></div>:items.map((item,index)=><article key={item.id} className="rounded-[22px] border border-slate-200 bg-white p-4"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-slate-100 text-sm font-black text-slate-700">{bankInitials(item.bank_name)}</div><div className="min-w-0 flex-1"><h3 className="truncate text-base font-black">{item.bank_name}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wide text-cyan-700">{item.account_type==='savings'?'Ahorros':'Corriente'} · {item.currency}</p><p className="mt-3 text-sm font-bold text-slate-900">{item.holder_name}</p><p className="mt-1 font-mono text-sm font-bold tracking-wide text-slate-500">{item.display_number||item.account_number}</p><p className="mt-2 text-xs font-semibold text-slate-400">{item.holder_id_type==='rnc'?'RNC':item.holder_id_type?'Cédula':'Identificación'} {item.holder_id_type?'guardada · no visible públicamente':'pendiente de completar'}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={()=>startEdit(item)} className="rounded-xl bg-slate-100 px-3 py-2.5 text-sm font-black text-slate-700">Editar</button><button type="button" onClick={()=>void remove(item.id)} className="rounded-xl bg-rose-50 px-3 py-2.5 text-sm font-black text-rose-700">Eliminar</button></div></article>)}</div>
  </section>
}


export default function SponsoredBankAccounts(){const params=new URLSearchParams(window.location.search);const fromSponsor=params.get('from')==='sponsor';const profileId=String(params.get('profile_id')||'');const backHref=fromSponsor?'/admin/sponsor':profileId?`/admin/sponsored?profile_id=${encodeURIComponent(profileId)}`:'/admin/sponsored';return <main className="min-h-screen bg-[#f7f9fc] px-4 py-7 font-['Inter'] text-slate-950"><div className="mx-auto max-w-[820px]"><a href={backHref} className="mb-4 inline-flex text-xs font-black text-cyan-700 no-underline">← {fromSponsor?'Panel patrocinador':'Mi presentación'}</a><SponsoredBankAccountsSection profileId={profileId||undefined}/></div></main>}
